/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.81.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// AnalyticsDataAPIService AnalyticsDataAPI service
type AnalyticsDataAPIService service

type ApiAnalyticsDataServiceGetBreakdownRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getBreakdownRequest *GetBreakdownRequest
}

func (r ApiAnalyticsDataServiceGetBreakdownRequest) GetBreakdownRequest(getBreakdownRequest GetBreakdownRequest) ApiAnalyticsDataServiceGetBreakdownRequest {
	r.getBreakdownRequest = &getBreakdownRequest
	return r
}

func (r ApiAnalyticsDataServiceGetBreakdownRequest) Execute() (*GetBreakdownResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetBreakdownExecute(r)
}

/*
AnalyticsDataServiceGetBreakdown Get dimension breakdown

Returns a ranked breakdown of events by any dimension (browser, platform, device type, country, city, visit type).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetBreakdownRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetBreakdown(ctx context.Context) ApiAnalyticsDataServiceGetBreakdownRequest {
	return ApiAnalyticsDataServiceGetBreakdownRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetBreakdownResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetBreakdownExecute(r ApiAnalyticsDataServiceGetBreakdownRequest) (*GetBreakdownResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetBreakdownResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetBreakdown")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/breakdown"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getBreakdownRequest == nil {
		return localVarReturnValue, nil, reportError("getBreakdownRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getBreakdownRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetDeviceDistributionRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getDeviceDistributionRequest *GetDeviceDistributionRequest
}

func (r ApiAnalyticsDataServiceGetDeviceDistributionRequest) GetDeviceDistributionRequest(getDeviceDistributionRequest GetDeviceDistributionRequest) ApiAnalyticsDataServiceGetDeviceDistributionRequest {
	r.getDeviceDistributionRequest = &getDeviceDistributionRequest
	return r
}

func (r ApiAnalyticsDataServiceGetDeviceDistributionRequest) Execute() (*GetDeviceDistributionResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetDeviceDistributionExecute(r)
}

/*
AnalyticsDataServiceGetDeviceDistribution Get device distribution

Retrieve event distribution across device types.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetDeviceDistributionRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetDeviceDistribution(ctx context.Context) ApiAnalyticsDataServiceGetDeviceDistributionRequest {
	return ApiAnalyticsDataServiceGetDeviceDistributionRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetDeviceDistributionResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetDeviceDistributionExecute(r ApiAnalyticsDataServiceGetDeviceDistributionRequest) (*GetDeviceDistributionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetDeviceDistributionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetDeviceDistribution")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/devices"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getDeviceDistributionRequest == nil {
		return localVarReturnValue, nil, reportError("getDeviceDistributionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getDeviceDistributionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetGeoBreakdownRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getGeoBreakdownRequest *GetGeoBreakdownRequest
}

func (r ApiAnalyticsDataServiceGetGeoBreakdownRequest) GetGeoBreakdownRequest(getGeoBreakdownRequest GetGeoBreakdownRequest) ApiAnalyticsDataServiceGetGeoBreakdownRequest {
	r.getGeoBreakdownRequest = &getGeoBreakdownRequest
	return r
}

func (r ApiAnalyticsDataServiceGetGeoBreakdownRequest) Execute() (*GetGeoBreakdownResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetGeoBreakdownExecute(r)
}

/*
AnalyticsDataServiceGetGeoBreakdown Get geographic breakdown

Retrieve geographic distribution of events grouped by country or city.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetGeoBreakdownRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetGeoBreakdown(ctx context.Context) ApiAnalyticsDataServiceGetGeoBreakdownRequest {
	return ApiAnalyticsDataServiceGetGeoBreakdownRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetGeoBreakdownResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetGeoBreakdownExecute(r ApiAnalyticsDataServiceGetGeoBreakdownRequest) (*GetGeoBreakdownResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetGeoBreakdownResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetGeoBreakdown")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/geo"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getGeoBreakdownRequest == nil {
		return localVarReturnValue, nil, reportError("getGeoBreakdownRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getGeoBreakdownRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getGroupedTimeSeriesRequest *GetGroupedTimeSeriesRequest
}

func (r ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest) GetGroupedTimeSeriesRequest(getGroupedTimeSeriesRequest GetGroupedTimeSeriesRequest) ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest {
	r.getGroupedTimeSeriesRequest = &getGroupedTimeSeriesRequest
	return r
}

func (r ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest) Execute() (*GetGroupedTimeSeriesResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetGroupedTimeSeriesExecute(r)
}

/*
AnalyticsDataServiceGetGroupedTimeSeries Get grouped time series

Retrieve time-bucketed event counts grouped by a dimension like country, city, device type, or visit type.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetGroupedTimeSeries(ctx context.Context) ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest {
	return ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetGroupedTimeSeriesResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetGroupedTimeSeriesExecute(r ApiAnalyticsDataServiceGetGroupedTimeSeriesRequest) (*GetGroupedTimeSeriesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetGroupedTimeSeriesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetGroupedTimeSeries")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/timeseries"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getGroupedTimeSeriesRequest == nil {
		return localVarReturnValue, nil, reportError("getGroupedTimeSeriesRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getGroupedTimeSeriesRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetHourOfDayDistributionRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getHourOfDayDistributionRequest *GetHourOfDayDistributionRequest
}

func (r ApiAnalyticsDataServiceGetHourOfDayDistributionRequest) GetHourOfDayDistributionRequest(getHourOfDayDistributionRequest GetHourOfDayDistributionRequest) ApiAnalyticsDataServiceGetHourOfDayDistributionRequest {
	r.getHourOfDayDistributionRequest = &getHourOfDayDistributionRequest
	return r
}

func (r ApiAnalyticsDataServiceGetHourOfDayDistributionRequest) Execute() (*GetHourOfDayDistributionResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetHourOfDayDistributionExecute(r)
}

/*
AnalyticsDataServiceGetHourOfDayDistribution Get hour of day distribution

Retrieve event counts aggregated by hour of day for identifying peak activity times.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetHourOfDayDistributionRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetHourOfDayDistribution(ctx context.Context) ApiAnalyticsDataServiceGetHourOfDayDistributionRequest {
	return ApiAnalyticsDataServiceGetHourOfDayDistributionRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetHourOfDayDistributionResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetHourOfDayDistributionExecute(r ApiAnalyticsDataServiceGetHourOfDayDistributionRequest) (*GetHourOfDayDistributionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetHourOfDayDistributionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetHourOfDayDistribution")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/hours"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getHourOfDayDistributionRequest == nil {
		return localVarReturnValue, nil, reportError("getHourOfDayDistributionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getHourOfDayDistributionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetTopLinksRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getTopLinksRequest *GetTopLinksRequest
}

func (r ApiAnalyticsDataServiceGetTopLinksRequest) GetTopLinksRequest(getTopLinksRequest GetTopLinksRequest) ApiAnalyticsDataServiceGetTopLinksRequest {
	r.getTopLinksRequest = &getTopLinksRequest
	return r
}

func (r ApiAnalyticsDataServiceGetTopLinksRequest) Execute() (*GetTopLinksResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetTopLinksExecute(r)
}

/*
AnalyticsDataServiceGetTopLinks Get top performing links

Retrieve links ranked by event count for identifying best performing QR codes and links.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetTopLinksRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetTopLinks(ctx context.Context) ApiAnalyticsDataServiceGetTopLinksRequest {
	return ApiAnalyticsDataServiceGetTopLinksRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetTopLinksResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetTopLinksExecute(r ApiAnalyticsDataServiceGetTopLinksRequest) (*GetTopLinksResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetTopLinksResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetTopLinks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/top-links"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getTopLinksRequest == nil {
		return localVarReturnValue, nil, reportError("getTopLinksRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getTopLinksRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAnalyticsDataServiceGetVisitorTrendsRequest struct {
	ctx context.Context
	ApiService *AnalyticsDataAPIService
	getVisitorTrendsRequest *GetVisitorTrendsRequest
}

func (r ApiAnalyticsDataServiceGetVisitorTrendsRequest) GetVisitorTrendsRequest(getVisitorTrendsRequest GetVisitorTrendsRequest) ApiAnalyticsDataServiceGetVisitorTrendsRequest {
	r.getVisitorTrendsRequest = &getVisitorTrendsRequest
	return r
}

func (r ApiAnalyticsDataServiceGetVisitorTrendsRequest) Execute() (*GetVisitorTrendsResponse, *http.Response, error) {
	return r.ApiService.AnalyticsDataServiceGetVisitorTrendsExecute(r)
}

/*
AnalyticsDataServiceGetVisitorTrends Get visitor trends

Retrieve new vs returning visitor counts over time.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAnalyticsDataServiceGetVisitorTrendsRequest
*/
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetVisitorTrends(ctx context.Context) ApiAnalyticsDataServiceGetVisitorTrendsRequest {
	return ApiAnalyticsDataServiceGetVisitorTrendsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetVisitorTrendsResponse
func (a *AnalyticsDataAPIService) AnalyticsDataServiceGetVisitorTrendsExecute(r ApiAnalyticsDataServiceGetVisitorTrendsRequest) (*GetVisitorTrendsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetVisitorTrendsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsDataAPIService.AnalyticsDataServiceGetVisitorTrends")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/analytics/visitors"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getVisitorTrendsRequest == nil {
		return localVarReturnValue, nil, reportError("getVisitorTrendsRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getVisitorTrendsRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
