/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.87.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// GoogleFormsIntegrationsAPIService GoogleFormsIntegrationsAPI service
type GoogleFormsIntegrationsAPIService service

type ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
	completeGoogleFormsOAuthRequest *CompleteGoogleFormsOAuthRequest
}

func (r ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest) CompleteGoogleFormsOAuthRequest(completeGoogleFormsOAuthRequest CompleteGoogleFormsOAuthRequest) ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest {
	r.completeGoogleFormsOAuthRequest = &completeGoogleFormsOAuthRequest
	return r
}

func (r ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest) Execute() (*CompleteGoogleFormsOAuthResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceCompleteOAuthExecute(r)
}

/*
GoogleFormsIntegrationsServiceCompleteOAuth Complete Google OAuth

Exchanges the Google authorization code for tokens and creates the workspace integration.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceCompleteOAuth(ctx context.Context) ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest {
	return ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CompleteGoogleFormsOAuthResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceCompleteOAuthExecute(r ApiGoogleFormsIntegrationsServiceCompleteOAuthRequest) (*CompleteGoogleFormsOAuthResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CompleteGoogleFormsOAuthResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceCompleteOAuth")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations/oauth/complete"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.completeGoogleFormsOAuthRequest == nil {
		return localVarReturnValue, nil, reportError("completeGoogleFormsOAuthRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.completeGoogleFormsOAuthRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceDeleteRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
}

func (r ApiGoogleFormsIntegrationsServiceDeleteRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceDeleteExecute(r)
}

/*
GoogleFormsIntegrationsServiceDelete Disconnect Google Forms integration

Disconnect and remove the Google Forms integration from the workspace.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceDeleteRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceDelete(ctx context.Context) ApiGoogleFormsIntegrationsServiceDeleteRequest {
	return ApiGoogleFormsIntegrationsServiceDeleteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceDeleteExecute(r ApiGoogleFormsIntegrationsServiceDeleteRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceGetRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
}

func (r ApiGoogleFormsIntegrationsServiceGetRequest) Execute() (*GetGoogleFormsIntegrationResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceGetExecute(r)
}

/*
GoogleFormsIntegrationsServiceGet Get Google Forms integration

Retrieve the Google Forms integration for the workspace.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceGetRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceGet(ctx context.Context) ApiGoogleFormsIntegrationsServiceGetRequest {
	return ApiGoogleFormsIntegrationsServiceGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetGoogleFormsIntegrationResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceGetExecute(r ApiGoogleFormsIntegrationsServiceGetRequest) (*GetGoogleFormsIntegrationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetGoogleFormsIntegrationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
}

func (r ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest) Execute() (*GetGoogleFormsOAuthURLResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceGetOAuthURLExecute(r)
}

/*
GoogleFormsIntegrationsServiceGetOAuthURL Get Google OAuth URL

Returns the Google OAuth authorization URL to initiate the connection flow.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceGetOAuthURL(ctx context.Context) ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest {
	return ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetGoogleFormsOAuthURLResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceGetOAuthURLExecute(r ApiGoogleFormsIntegrationsServiceGetOAuthURLRequest) (*GetGoogleFormsOAuthURLResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetGoogleFormsOAuthURLResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceGetOAuthURL")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations/oauth-url"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
}

func (r ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest) Execute() (*ListDetectedGoogleFormsResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceListDetectedFormsExecute(r)
}

/*
GoogleFormsIntegrationsServiceListDetectedForms List detected Google Forms

Returns Google Forms auto-detected from workspace links that have a Google Form as their redirect destination.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceListDetectedForms(ctx context.Context) ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest {
	return ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ListDetectedGoogleFormsResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceListDetectedFormsExecute(r ApiGoogleFormsIntegrationsServiceListDetectedFormsRequest) (*ListDetectedGoogleFormsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListDetectedGoogleFormsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceListDetectedForms")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations/detected-forms"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceSyncNowRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
	body *map[string]interface{}
}

func (r ApiGoogleFormsIntegrationsServiceSyncNowRequest) Body(body map[string]interface{}) ApiGoogleFormsIntegrationsServiceSyncNowRequest {
	r.body = &body
	return r
}

func (r ApiGoogleFormsIntegrationsServiceSyncNowRequest) Execute() (*SyncGoogleFormsResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceSyncNowExecute(r)
}

/*
GoogleFormsIntegrationsServiceSyncNow Sync now

Trigger an immediate sync of new Google Forms responses from all detected forms.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceSyncNowRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceSyncNow(ctx context.Context) ApiGoogleFormsIntegrationsServiceSyncNowRequest {
	return ApiGoogleFormsIntegrationsServiceSyncNowRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SyncGoogleFormsResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceSyncNowExecute(r ApiGoogleFormsIntegrationsServiceSyncNowRequest) (*SyncGoogleFormsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SyncGoogleFormsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceSyncNow")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations/sync"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGoogleFormsIntegrationsServiceUpdateRequest struct {
	ctx context.Context
	ApiService *GoogleFormsIntegrationsAPIService
	updateGoogleFormsIntegrationRequest *UpdateGoogleFormsIntegrationRequest
}

func (r ApiGoogleFormsIntegrationsServiceUpdateRequest) UpdateGoogleFormsIntegrationRequest(updateGoogleFormsIntegrationRequest UpdateGoogleFormsIntegrationRequest) ApiGoogleFormsIntegrationsServiceUpdateRequest {
	r.updateGoogleFormsIntegrationRequest = &updateGoogleFormsIntegrationRequest
	return r
}

func (r ApiGoogleFormsIntegrationsServiceUpdateRequest) Execute() (*UpdateGoogleFormsIntegrationResponse, *http.Response, error) {
	return r.ApiService.GoogleFormsIntegrationsServiceUpdateExecute(r)
}

/*
GoogleFormsIntegrationsServiceUpdate Update Google Forms integration

Update the integration status (pause or resume syncing).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGoogleFormsIntegrationsServiceUpdateRequest
*/
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceUpdate(ctx context.Context) ApiGoogleFormsIntegrationsServiceUpdateRequest {
	return ApiGoogleFormsIntegrationsServiceUpdateRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return UpdateGoogleFormsIntegrationResponse
func (a *GoogleFormsIntegrationsAPIService) GoogleFormsIntegrationsServiceUpdateExecute(r ApiGoogleFormsIntegrationsServiceUpdateRequest) (*UpdateGoogleFormsIntegrationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UpdateGoogleFormsIntegrationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GoogleFormsIntegrationsAPIService.GoogleFormsIntegrationsServiceUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/google-forms-integrations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateGoogleFormsIntegrationRequest == nil {
		return localVarReturnValue, nil, reportError("updateGoogleFormsIntegrationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateGoogleFormsIntegrationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
