/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.43.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the AddWorkflowStepRelationshipResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddWorkflowStepRelationshipResponse{}

// AddWorkflowStepRelationshipResponse struct for AddWorkflowStepRelationshipResponse
type AddWorkflowStepRelationshipResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewAddWorkflowStepRelationshipResponse instantiates a new AddWorkflowStepRelationshipResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddWorkflowStepRelationshipResponse() *AddWorkflowStepRelationshipResponse {
	this := AddWorkflowStepRelationshipResponse{}
	return &this
}

// NewAddWorkflowStepRelationshipResponseWithDefaults instantiates a new AddWorkflowStepRelationshipResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddWorkflowStepRelationshipResponseWithDefaults() *AddWorkflowStepRelationshipResponse {
	this := AddWorkflowStepRelationshipResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AddWorkflowStepRelationshipResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddWorkflowStepRelationshipResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AddWorkflowStepRelationshipResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AddWorkflowStepRelationshipResponse) SetMessage(v string) {
	o.Message = &v
}

func (o AddWorkflowStepRelationshipResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddWorkflowStepRelationshipResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableAddWorkflowStepRelationshipResponse struct {
	value *AddWorkflowStepRelationshipResponse
	isSet bool
}

func (v NullableAddWorkflowStepRelationshipResponse) Get() *AddWorkflowStepRelationshipResponse {
	return v.value
}

func (v *NullableAddWorkflowStepRelationshipResponse) Set(val *AddWorkflowStepRelationshipResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddWorkflowStepRelationshipResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddWorkflowStepRelationshipResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddWorkflowStepRelationshipResponse(val *AddWorkflowStepRelationshipResponse) *NullableAddWorkflowStepRelationshipResponse {
	return &NullableAddWorkflowStepRelationshipResponse{value: val, isSet: true}
}

func (v NullableAddWorkflowStepRelationshipResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddWorkflowStepRelationshipResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


