/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.118.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"fmt"
)

// WidgetTabView WidgetTabView says how a tab draws what it fetched.   - WIDGET_TAB_VIEW_UNSPECIFIED: The widget's own chart type.  - WIDGET_TAB_VIEW_MAP: A world map, which needs rows carrying a country code.
type WidgetTabView string

// List of WidgetTabView
const (
	WIDGETTABVIEW_WIDGET_TAB_VIEW_UNSPECIFIED WidgetTabView = "WIDGET_TAB_VIEW_UNSPECIFIED"
	WIDGETTABVIEW_WIDGET_TAB_VIEW_CHART WidgetTabView = "WIDGET_TAB_VIEW_CHART"
	WIDGETTABVIEW_WIDGET_TAB_VIEW_MAP WidgetTabView = "WIDGET_TAB_VIEW_MAP"
)

// All allowed values of WidgetTabView enum
var AllowedWidgetTabViewEnumValues = []WidgetTabView{
	"WIDGET_TAB_VIEW_UNSPECIFIED",
	"WIDGET_TAB_VIEW_CHART",
	"WIDGET_TAB_VIEW_MAP",
}

func (v *WidgetTabView) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WidgetTabView(value)
	for _, existing := range AllowedWidgetTabViewEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WidgetTabView", value)
}

// NewWidgetTabViewFromValue returns a pointer to a valid WidgetTabView
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWidgetTabViewFromValue(v string) (*WidgetTabView, error) {
	ev := WidgetTabView(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WidgetTabView: valid values are %v", v, AllowedWidgetTabViewEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WidgetTabView) IsValid() bool {
	for _, existing := range AllowedWidgetTabViewEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WidgetTabView value
func (v WidgetTabView) Ptr() *WidgetTabView {
	return &v
}

type NullableWidgetTabView struct {
	value *WidgetTabView
	isSet bool
}

func (v NullableWidgetTabView) Get() *WidgetTabView {
	return v.value
}

func (v *NullableWidgetTabView) Set(val *WidgetTabView) {
	v.value = val
	v.isSet = true
}

func (v NullableWidgetTabView) IsSet() bool {
	return v.isSet
}

func (v *NullableWidgetTabView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidgetTabView(val *WidgetTabView) *NullableWidgetTabView {
	return &NullableWidgetTabView{value: val, isSet: true}
}

func (v NullableWidgetTabView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidgetTabView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

