/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the VisitorDataConditionOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VisitorDataConditionOption{}

// VisitorDataConditionOption Visitor data condition option for EVENT_ACTION_VISITOR_DATA_CONDITION.
type VisitorDataConditionOption struct {
	AttributeKey *string `json:"attributeKey,omitempty"`
	ComparisonValue *string `json:"comparisonValue,omitempty"`
	Id *string `json:"id,omitempty"`
	NextStepId *string `json:"nextStepId,omitempty"`
	Operator *string `json:"operator,omitempty"`
}

// NewVisitorDataConditionOption instantiates a new VisitorDataConditionOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVisitorDataConditionOption() *VisitorDataConditionOption {
	this := VisitorDataConditionOption{}
	return &this
}

// NewVisitorDataConditionOptionWithDefaults instantiates a new VisitorDataConditionOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVisitorDataConditionOptionWithDefaults() *VisitorDataConditionOption {
	this := VisitorDataConditionOption{}
	return &this
}

// GetAttributeKey returns the AttributeKey field value if set, zero value otherwise.
func (o *VisitorDataConditionOption) GetAttributeKey() string {
	if o == nil || IsNil(o.AttributeKey) {
		var ret string
		return ret
	}
	return *o.AttributeKey
}

// GetAttributeKeyOk returns a tuple with the AttributeKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionOption) GetAttributeKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeKey) {
		return nil, false
	}
	return o.AttributeKey, true
}

// HasAttributeKey returns a boolean if a field has been set.
func (o *VisitorDataConditionOption) HasAttributeKey() bool {
	if o != nil && !IsNil(o.AttributeKey) {
		return true
	}

	return false
}

// SetAttributeKey gets a reference to the given string and assigns it to the AttributeKey field.
func (o *VisitorDataConditionOption) SetAttributeKey(v string) {
	o.AttributeKey = &v
}

// GetComparisonValue returns the ComparisonValue field value if set, zero value otherwise.
func (o *VisitorDataConditionOption) GetComparisonValue() string {
	if o == nil || IsNil(o.ComparisonValue) {
		var ret string
		return ret
	}
	return *o.ComparisonValue
}

// GetComparisonValueOk returns a tuple with the ComparisonValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionOption) GetComparisonValueOk() (*string, bool) {
	if o == nil || IsNil(o.ComparisonValue) {
		return nil, false
	}
	return o.ComparisonValue, true
}

// HasComparisonValue returns a boolean if a field has been set.
func (o *VisitorDataConditionOption) HasComparisonValue() bool {
	if o != nil && !IsNil(o.ComparisonValue) {
		return true
	}

	return false
}

// SetComparisonValue gets a reference to the given string and assigns it to the ComparisonValue field.
func (o *VisitorDataConditionOption) SetComparisonValue(v string) {
	o.ComparisonValue = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VisitorDataConditionOption) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionOption) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VisitorDataConditionOption) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VisitorDataConditionOption) SetId(v string) {
	o.Id = &v
}

// GetNextStepId returns the NextStepId field value if set, zero value otherwise.
func (o *VisitorDataConditionOption) GetNextStepId() string {
	if o == nil || IsNil(o.NextStepId) {
		var ret string
		return ret
	}
	return *o.NextStepId
}

// GetNextStepIdOk returns a tuple with the NextStepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionOption) GetNextStepIdOk() (*string, bool) {
	if o == nil || IsNil(o.NextStepId) {
		return nil, false
	}
	return o.NextStepId, true
}

// HasNextStepId returns a boolean if a field has been set.
func (o *VisitorDataConditionOption) HasNextStepId() bool {
	if o != nil && !IsNil(o.NextStepId) {
		return true
	}

	return false
}

// SetNextStepId gets a reference to the given string and assigns it to the NextStepId field.
func (o *VisitorDataConditionOption) SetNextStepId(v string) {
	o.NextStepId = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *VisitorDataConditionOption) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionOption) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *VisitorDataConditionOption) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *VisitorDataConditionOption) SetOperator(v string) {
	o.Operator = &v
}

func (o VisitorDataConditionOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VisitorDataConditionOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeKey) {
		toSerialize["attributeKey"] = o.AttributeKey
	}
	if !IsNil(o.ComparisonValue) {
		toSerialize["comparisonValue"] = o.ComparisonValue
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NextStepId) {
		toSerialize["nextStepId"] = o.NextStepId
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	return toSerialize, nil
}

type NullableVisitorDataConditionOption struct {
	value *VisitorDataConditionOption
	isSet bool
}

func (v NullableVisitorDataConditionOption) Get() *VisitorDataConditionOption {
	return v.value
}

func (v *NullableVisitorDataConditionOption) Set(val *VisitorDataConditionOption) {
	v.value = val
	v.isSet = true
}

func (v NullableVisitorDataConditionOption) IsSet() bool {
	return v.isSet
}

func (v *NullableVisitorDataConditionOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVisitorDataConditionOption(val *VisitorDataConditionOption) *NullableVisitorDataConditionOption {
	return &NullableVisitorDataConditionOption{value: val, isSet: true}
}

func (v NullableVisitorDataConditionOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVisitorDataConditionOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


