/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.84.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"fmt"
)

// GoogleFormsIntegrationStatus the model 'GoogleFormsIntegrationStatus'
type GoogleFormsIntegrationStatus string

// List of GoogleFormsIntegrationStatus
const (
	GOOGLEFORMSINTEGRATIONSTATUS_GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED GoogleFormsIntegrationStatus = "GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED"
	GOOGLEFORMSINTEGRATIONSTATUS_GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE GoogleFormsIntegrationStatus = "GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE"
	GOOGLEFORMSINTEGRATIONSTATUS_GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED GoogleFormsIntegrationStatus = "GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED"
	GOOGLEFORMSINTEGRATIONSTATUS_GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED GoogleFormsIntegrationStatus = "GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED"
)

// All allowed values of GoogleFormsIntegrationStatus enum
var AllowedGoogleFormsIntegrationStatusEnumValues = []GoogleFormsIntegrationStatus{
	"GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED",
	"GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE",
	"GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED",
	"GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED",
}

func (v *GoogleFormsIntegrationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GoogleFormsIntegrationStatus(value)
	for _, existing := range AllowedGoogleFormsIntegrationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GoogleFormsIntegrationStatus", value)
}

// NewGoogleFormsIntegrationStatusFromValue returns a pointer to a valid GoogleFormsIntegrationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGoogleFormsIntegrationStatusFromValue(v string) (*GoogleFormsIntegrationStatus, error) {
	ev := GoogleFormsIntegrationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GoogleFormsIntegrationStatus: valid values are %v", v, AllowedGoogleFormsIntegrationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GoogleFormsIntegrationStatus) IsValid() bool {
	for _, existing := range AllowedGoogleFormsIntegrationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GoogleFormsIntegrationStatus value
func (v GoogleFormsIntegrationStatus) Ptr() *GoogleFormsIntegrationStatus {
	return &v
}

type NullableGoogleFormsIntegrationStatus struct {
	value *GoogleFormsIntegrationStatus
	isSet bool
}

func (v NullableGoogleFormsIntegrationStatus) Get() *GoogleFormsIntegrationStatus {
	return v.value
}

func (v *NullableGoogleFormsIntegrationStatus) Set(val *GoogleFormsIntegrationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleFormsIntegrationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleFormsIntegrationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleFormsIntegrationStatus(val *GoogleFormsIntegrationStatus) *NullableGoogleFormsIntegrationStatus {
	return &NullableGoogleFormsIntegrationStatus{value: val, isSet: true}
}

func (v NullableGoogleFormsIntegrationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleFormsIntegrationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

