/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.122.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"fmt"
)

// QrcodeTemplateScope QrcodeTemplateScope selects which templates a list call returns.   - QRCODE_TEMPLATE_SCOPE_UNSPECIFIED: Defaults to QRCODE_TEMPLATE_SCOPE_WORKSPACE.  - QRCODE_TEMPLATE_SCOPE_WORKSPACE: Only templates owned by the caller's workspace.  - QRCODE_TEMPLATE_SCOPE_AVAILABLE: Every template the workspace may use: its own, built-in ones, and templates published by other workspaces.
type QrcodeTemplateScope string

// List of QrcodeTemplateScope
const (
	QRCODETEMPLATESCOPE_QRCODE_TEMPLATE_SCOPE_UNSPECIFIED QrcodeTemplateScope = "QRCODE_TEMPLATE_SCOPE_UNSPECIFIED"
	QRCODETEMPLATESCOPE_QRCODE_TEMPLATE_SCOPE_WORKSPACE QrcodeTemplateScope = "QRCODE_TEMPLATE_SCOPE_WORKSPACE"
	QRCODETEMPLATESCOPE_QRCODE_TEMPLATE_SCOPE_AVAILABLE QrcodeTemplateScope = "QRCODE_TEMPLATE_SCOPE_AVAILABLE"
)

// All allowed values of QrcodeTemplateScope enum
var AllowedQrcodeTemplateScopeEnumValues = []QrcodeTemplateScope{
	"QRCODE_TEMPLATE_SCOPE_UNSPECIFIED",
	"QRCODE_TEMPLATE_SCOPE_WORKSPACE",
	"QRCODE_TEMPLATE_SCOPE_AVAILABLE",
}

func (v *QrcodeTemplateScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := QrcodeTemplateScope(value)
	for _, existing := range AllowedQrcodeTemplateScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid QrcodeTemplateScope", value)
}

// NewQrcodeTemplateScopeFromValue returns a pointer to a valid QrcodeTemplateScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewQrcodeTemplateScopeFromValue(v string) (*QrcodeTemplateScope, error) {
	ev := QrcodeTemplateScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for QrcodeTemplateScope: valid values are %v", v, AllowedQrcodeTemplateScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v QrcodeTemplateScope) IsValid() bool {
	for _, existing := range AllowedQrcodeTemplateScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to QrcodeTemplateScope value
func (v QrcodeTemplateScope) Ptr() *QrcodeTemplateScope {
	return &v
}

type NullableQrcodeTemplateScope struct {
	value *QrcodeTemplateScope
	isSet bool
}

func (v NullableQrcodeTemplateScope) Get() *QrcodeTemplateScope {
	return v.value
}

func (v *NullableQrcodeTemplateScope) Set(val *QrcodeTemplateScope) {
	v.value = val
	v.isSet = true
}

func (v NullableQrcodeTemplateScope) IsSet() bool {
	return v.isSet
}

func (v *NullableQrcodeTemplateScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQrcodeTemplateScope(val *QrcodeTemplateScope) *NullableQrcodeTemplateScope {
	return &NullableQrcodeTemplateScope{value: val, isSet: true}
}

func (v NullableQrcodeTemplateScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQrcodeTemplateScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

