/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.118.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the DashboardConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardConfig{}

// DashboardConfig struct for DashboardConfig
type DashboardConfig struct {
	// Width of the grid the widget positions and sizes are expressed in. Absent or 0 means the legacy two-column grid, where w=1 is half-width and w=2 is full-width. New dashboards use 8.
	GridColumns *int32 `json:"gridColumns,omitempty"`
	Widgets []DashboardWidget `json:"widgets,omitempty"`
}

// NewDashboardConfig instantiates a new DashboardConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardConfig() *DashboardConfig {
	this := DashboardConfig{}
	return &this
}

// NewDashboardConfigWithDefaults instantiates a new DashboardConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardConfigWithDefaults() *DashboardConfig {
	this := DashboardConfig{}
	return &this
}

// GetGridColumns returns the GridColumns field value if set, zero value otherwise.
func (o *DashboardConfig) GetGridColumns() int32 {
	if o == nil || IsNil(o.GridColumns) {
		var ret int32
		return ret
	}
	return *o.GridColumns
}

// GetGridColumnsOk returns a tuple with the GridColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardConfig) GetGridColumnsOk() (*int32, bool) {
	if o == nil || IsNil(o.GridColumns) {
		return nil, false
	}
	return o.GridColumns, true
}

// HasGridColumns returns a boolean if a field has been set.
func (o *DashboardConfig) HasGridColumns() bool {
	if o != nil && !IsNil(o.GridColumns) {
		return true
	}

	return false
}

// SetGridColumns gets a reference to the given int32 and assigns it to the GridColumns field.
func (o *DashboardConfig) SetGridColumns(v int32) {
	o.GridColumns = &v
}

// GetWidgets returns the Widgets field value if set, zero value otherwise.
func (o *DashboardConfig) GetWidgets() []DashboardWidget {
	if o == nil || IsNil(o.Widgets) {
		var ret []DashboardWidget
		return ret
	}
	return o.Widgets
}

// GetWidgetsOk returns a tuple with the Widgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardConfig) GetWidgetsOk() ([]DashboardWidget, bool) {
	if o == nil || IsNil(o.Widgets) {
		return nil, false
	}
	return o.Widgets, true
}

// HasWidgets returns a boolean if a field has been set.
func (o *DashboardConfig) HasWidgets() bool {
	if o != nil && !IsNil(o.Widgets) {
		return true
	}

	return false
}

// SetWidgets gets a reference to the given []DashboardWidget and assigns it to the Widgets field.
func (o *DashboardConfig) SetWidgets(v []DashboardWidget) {
	o.Widgets = v
}

func (o DashboardConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GridColumns) {
		toSerialize["gridColumns"] = o.GridColumns
	}
	if !IsNil(o.Widgets) {
		toSerialize["widgets"] = o.Widgets
	}
	return toSerialize, nil
}

type NullableDashboardConfig struct {
	value *DashboardConfig
	isSet bool
}

func (v NullableDashboardConfig) Get() *DashboardConfig {
	return v.value
}

func (v *NullableDashboardConfig) Set(val *DashboardConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardConfig(val *DashboardConfig) *NullableDashboardConfig {
	return &NullableDashboardConfig{value: val, isSet: true}
}

func (v NullableDashboardConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


