/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.124.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the ImportPageThemeTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportPageThemeTemplateRequest{}

// ImportPageThemeTemplateRequest struct for ImportPageThemeTemplateRequest
type ImportPageThemeTemplateRequest struct {
	// The slug of the public page theme template to import into your workspace
	Slug *string `json:"slug,omitempty"`
}

// NewImportPageThemeTemplateRequest instantiates a new ImportPageThemeTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportPageThemeTemplateRequest() *ImportPageThemeTemplateRequest {
	this := ImportPageThemeTemplateRequest{}
	return &this
}

// NewImportPageThemeTemplateRequestWithDefaults instantiates a new ImportPageThemeTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportPageThemeTemplateRequestWithDefaults() *ImportPageThemeTemplateRequest {
	this := ImportPageThemeTemplateRequest{}
	return &this
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ImportPageThemeTemplateRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPageThemeTemplateRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ImportPageThemeTemplateRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ImportPageThemeTemplateRequest) SetSlug(v string) {
	o.Slug = &v
}

func (o ImportPageThemeTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportPageThemeTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	return toSerialize, nil
}

type NullableImportPageThemeTemplateRequest struct {
	value *ImportPageThemeTemplateRequest
	isSet bool
}

func (v NullableImportPageThemeTemplateRequest) Get() *ImportPageThemeTemplateRequest {
	return v.value
}

func (v *NullableImportPageThemeTemplateRequest) Set(val *ImportPageThemeTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImportPageThemeTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImportPageThemeTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportPageThemeTemplateRequest(val *ImportPageThemeTemplateRequest) *NullableImportPageThemeTemplateRequest {
	return &NullableImportPageThemeTemplateRequest{value: val, isSet: true}
}

func (v NullableImportPageThemeTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportPageThemeTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


