/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the CreateCustomDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomDomainRequest{}

// CreateCustomDomainRequest struct for CreateCustomDomainRequest
type CreateCustomDomainRequest struct {
	// The domain name to register. It must be a valid DNS and not already registered in Linkbreakers. Subdomains are also supported.
	Name *string `json:"name,omitempty"`
}

// NewCreateCustomDomainRequest instantiates a new CreateCustomDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomDomainRequest() *CreateCustomDomainRequest {
	this := CreateCustomDomainRequest{}
	return &this
}

// NewCreateCustomDomainRequestWithDefaults instantiates a new CreateCustomDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomDomainRequestWithDefaults() *CreateCustomDomainRequest {
	this := CreateCustomDomainRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateCustomDomainRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCustomDomainRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateCustomDomainRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateCustomDomainRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateCustomDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateCustomDomainRequest struct {
	value *CreateCustomDomainRequest
	isSet bool
}

func (v NullableCreateCustomDomainRequest) Get() *CreateCustomDomainRequest {
	return v.value
}

func (v *NullableCreateCustomDomainRequest) Set(val *CreateCustomDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomDomainRequest(val *CreateCustomDomainRequest) *NullableCreateCustomDomainRequest {
	return &NullableCreateCustomDomainRequest{value: val, isSet: true}
}

func (v NullableCreateCustomDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


