/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWorkspaceTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkspaceTokenRequest{}

// CreateWorkspaceTokenRequest struct for CreateWorkspaceTokenRequest
type CreateWorkspaceTokenRequest struct {
	KeyType WorkspaceTokenKeyType `json:"keyType"`
	Name *string `json:"name,omitempty"`
}

type _CreateWorkspaceTokenRequest CreateWorkspaceTokenRequest

// NewCreateWorkspaceTokenRequest instantiates a new CreateWorkspaceTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkspaceTokenRequest(keyType WorkspaceTokenKeyType) *CreateWorkspaceTokenRequest {
	this := CreateWorkspaceTokenRequest{}
	this.KeyType = keyType
	return &this
}

// NewCreateWorkspaceTokenRequestWithDefaults instantiates a new CreateWorkspaceTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkspaceTokenRequestWithDefaults() *CreateWorkspaceTokenRequest {
	this := CreateWorkspaceTokenRequest{}
	return &this
}

// GetKeyType returns the KeyType field value
func (o *CreateWorkspaceTokenRequest) GetKeyType() WorkspaceTokenKeyType {
	if o == nil {
		var ret WorkspaceTokenKeyType
		return ret
	}

	return o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceTokenRequest) GetKeyTypeOk() (*WorkspaceTokenKeyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyType, true
}

// SetKeyType sets field value
func (o *CreateWorkspaceTokenRequest) SetKeyType(v WorkspaceTokenKeyType) {
	o.KeyType = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateWorkspaceTokenRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceTokenRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateWorkspaceTokenRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateWorkspaceTokenRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateWorkspaceTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkspaceTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyType"] = o.KeyType
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *CreateWorkspaceTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keyType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkspaceTokenRequest := _CreateWorkspaceTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkspaceTokenRequest)

	if err != nil {
		return err
	}

	*o = CreateWorkspaceTokenRequest(varCreateWorkspaceTokenRequest)

	return err
}

type NullableCreateWorkspaceTokenRequest struct {
	value *CreateWorkspaceTokenRequest
	isSet bool
}

func (v NullableCreateWorkspaceTokenRequest) Get() *CreateWorkspaceTokenRequest {
	return v.value
}

func (v *NullableCreateWorkspaceTokenRequest) Set(val *CreateWorkspaceTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkspaceTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkspaceTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkspaceTokenRequest(val *CreateWorkspaceTokenRequest) *NullableCreateWorkspaceTokenRequest {
	return &NullableCreateWorkspaceTokenRequest{value: val, isSet: true}
}

func (v NullableCreateWorkspaceTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkspaceTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


