/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.124.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the PublishPageThemeTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishPageThemeTemplateResponse{}

// PublishPageThemeTemplateResponse struct for PublishPageThemeTemplateResponse
type PublishPageThemeTemplateResponse struct {
	PageThemeTemplate *PageThemeTemplate `json:"pageThemeTemplate,omitempty"`
}

// NewPublishPageThemeTemplateResponse instantiates a new PublishPageThemeTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishPageThemeTemplateResponse() *PublishPageThemeTemplateResponse {
	this := PublishPageThemeTemplateResponse{}
	return &this
}

// NewPublishPageThemeTemplateResponseWithDefaults instantiates a new PublishPageThemeTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishPageThemeTemplateResponseWithDefaults() *PublishPageThemeTemplateResponse {
	this := PublishPageThemeTemplateResponse{}
	return &this
}

// GetPageThemeTemplate returns the PageThemeTemplate field value if set, zero value otherwise.
func (o *PublishPageThemeTemplateResponse) GetPageThemeTemplate() PageThemeTemplate {
	if o == nil || IsNil(o.PageThemeTemplate) {
		var ret PageThemeTemplate
		return ret
	}
	return *o.PageThemeTemplate
}

// GetPageThemeTemplateOk returns a tuple with the PageThemeTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishPageThemeTemplateResponse) GetPageThemeTemplateOk() (*PageThemeTemplate, bool) {
	if o == nil || IsNil(o.PageThemeTemplate) {
		return nil, false
	}
	return o.PageThemeTemplate, true
}

// HasPageThemeTemplate returns a boolean if a field has been set.
func (o *PublishPageThemeTemplateResponse) HasPageThemeTemplate() bool {
	if o != nil && !IsNil(o.PageThemeTemplate) {
		return true
	}

	return false
}

// SetPageThemeTemplate gets a reference to the given PageThemeTemplate and assigns it to the PageThemeTemplate field.
func (o *PublishPageThemeTemplateResponse) SetPageThemeTemplate(v PageThemeTemplate) {
	o.PageThemeTemplate = &v
}

func (o PublishPageThemeTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishPageThemeTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageThemeTemplate) {
		toSerialize["pageThemeTemplate"] = o.PageThemeTemplate
	}
	return toSerialize, nil
}

type NullablePublishPageThemeTemplateResponse struct {
	value *PublishPageThemeTemplateResponse
	isSet bool
}

func (v NullablePublishPageThemeTemplateResponse) Get() *PublishPageThemeTemplateResponse {
	return v.value
}

func (v *NullablePublishPageThemeTemplateResponse) Set(val *PublishPageThemeTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishPageThemeTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishPageThemeTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishPageThemeTemplateResponse(val *PublishPageThemeTemplateResponse) *NullablePublishPageThemeTemplateResponse {
	return &NullablePublishPageThemeTemplateResponse{value: val, isSet: true}
}

func (v NullablePublishPageThemeTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishPageThemeTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


