/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.87.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the ResolveStepCollisionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveStepCollisionsResponse{}

// ResolveStepCollisionsResponse struct for ResolveStepCollisionsResponse
type ResolveStepCollisionsResponse struct {
	StepsRepositioned *int32 `json:"stepsRepositioned,omitempty"`
}

// NewResolveStepCollisionsResponse instantiates a new ResolveStepCollisionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveStepCollisionsResponse() *ResolveStepCollisionsResponse {
	this := ResolveStepCollisionsResponse{}
	return &this
}

// NewResolveStepCollisionsResponseWithDefaults instantiates a new ResolveStepCollisionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveStepCollisionsResponseWithDefaults() *ResolveStepCollisionsResponse {
	this := ResolveStepCollisionsResponse{}
	return &this
}

// GetStepsRepositioned returns the StepsRepositioned field value if set, zero value otherwise.
func (o *ResolveStepCollisionsResponse) GetStepsRepositioned() int32 {
	if o == nil || IsNil(o.StepsRepositioned) {
		var ret int32
		return ret
	}
	return *o.StepsRepositioned
}

// GetStepsRepositionedOk returns a tuple with the StepsRepositioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResolveStepCollisionsResponse) GetStepsRepositionedOk() (*int32, bool) {
	if o == nil || IsNil(o.StepsRepositioned) {
		return nil, false
	}
	return o.StepsRepositioned, true
}

// HasStepsRepositioned returns a boolean if a field has been set.
func (o *ResolveStepCollisionsResponse) HasStepsRepositioned() bool {
	if o != nil && !IsNil(o.StepsRepositioned) {
		return true
	}

	return false
}

// SetStepsRepositioned gets a reference to the given int32 and assigns it to the StepsRepositioned field.
func (o *ResolveStepCollisionsResponse) SetStepsRepositioned(v int32) {
	o.StepsRepositioned = &v
}

func (o ResolveStepCollisionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveStepCollisionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StepsRepositioned) {
		toSerialize["stepsRepositioned"] = o.StepsRepositioned
	}
	return toSerialize, nil
}

type NullableResolveStepCollisionsResponse struct {
	value *ResolveStepCollisionsResponse
	isSet bool
}

func (v NullableResolveStepCollisionsResponse) Get() *ResolveStepCollisionsResponse {
	return v.value
}

func (v *NullableResolveStepCollisionsResponse) Set(val *ResolveStepCollisionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveStepCollisionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveStepCollisionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveStepCollisionsResponse(val *ResolveStepCollisionsResponse) *NullableResolveStepCollisionsResponse {
	return &NullableResolveStepCollisionsResponse{value: val, isSet: true}
}

func (v NullableResolveStepCollisionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveStepCollisionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


