/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the VisitorDataConditionTraceOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VisitorDataConditionTraceOption{}

// VisitorDataConditionTraceOption struct for VisitorDataConditionTraceOption
type VisitorDataConditionTraceOption struct {
	AttributeFound *bool `json:"attributeFound,omitempty"`
	AttributeKey *string `json:"attributeKey,omitempty"`
	ComparisonValue *string `json:"comparisonValue,omitempty"`
	HasRoute *bool `json:"hasRoute,omitempty"`
	Matched *bool `json:"matched,omitempty"`
	ObservedValue *string `json:"observedValue,omitempty"`
	Operator *string `json:"operator,omitempty"`
}

// NewVisitorDataConditionTraceOption instantiates a new VisitorDataConditionTraceOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVisitorDataConditionTraceOption() *VisitorDataConditionTraceOption {
	this := VisitorDataConditionTraceOption{}
	return &this
}

// NewVisitorDataConditionTraceOptionWithDefaults instantiates a new VisitorDataConditionTraceOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVisitorDataConditionTraceOptionWithDefaults() *VisitorDataConditionTraceOption {
	this := VisitorDataConditionTraceOption{}
	return &this
}

// GetAttributeFound returns the AttributeFound field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetAttributeFound() bool {
	if o == nil || IsNil(o.AttributeFound) {
		var ret bool
		return ret
	}
	return *o.AttributeFound
}

// GetAttributeFoundOk returns a tuple with the AttributeFound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetAttributeFoundOk() (*bool, bool) {
	if o == nil || IsNil(o.AttributeFound) {
		return nil, false
	}
	return o.AttributeFound, true
}

// HasAttributeFound returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasAttributeFound() bool {
	if o != nil && !IsNil(o.AttributeFound) {
		return true
	}

	return false
}

// SetAttributeFound gets a reference to the given bool and assigns it to the AttributeFound field.
func (o *VisitorDataConditionTraceOption) SetAttributeFound(v bool) {
	o.AttributeFound = &v
}

// GetAttributeKey returns the AttributeKey field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetAttributeKey() string {
	if o == nil || IsNil(o.AttributeKey) {
		var ret string
		return ret
	}
	return *o.AttributeKey
}

// GetAttributeKeyOk returns a tuple with the AttributeKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetAttributeKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeKey) {
		return nil, false
	}
	return o.AttributeKey, true
}

// HasAttributeKey returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasAttributeKey() bool {
	if o != nil && !IsNil(o.AttributeKey) {
		return true
	}

	return false
}

// SetAttributeKey gets a reference to the given string and assigns it to the AttributeKey field.
func (o *VisitorDataConditionTraceOption) SetAttributeKey(v string) {
	o.AttributeKey = &v
}

// GetComparisonValue returns the ComparisonValue field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetComparisonValue() string {
	if o == nil || IsNil(o.ComparisonValue) {
		var ret string
		return ret
	}
	return *o.ComparisonValue
}

// GetComparisonValueOk returns a tuple with the ComparisonValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetComparisonValueOk() (*string, bool) {
	if o == nil || IsNil(o.ComparisonValue) {
		return nil, false
	}
	return o.ComparisonValue, true
}

// HasComparisonValue returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasComparisonValue() bool {
	if o != nil && !IsNil(o.ComparisonValue) {
		return true
	}

	return false
}

// SetComparisonValue gets a reference to the given string and assigns it to the ComparisonValue field.
func (o *VisitorDataConditionTraceOption) SetComparisonValue(v string) {
	o.ComparisonValue = &v
}

// GetHasRoute returns the HasRoute field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetHasRoute() bool {
	if o == nil || IsNil(o.HasRoute) {
		var ret bool
		return ret
	}
	return *o.HasRoute
}

// GetHasRouteOk returns a tuple with the HasRoute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetHasRouteOk() (*bool, bool) {
	if o == nil || IsNil(o.HasRoute) {
		return nil, false
	}
	return o.HasRoute, true
}

// HasHasRoute returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasHasRoute() bool {
	if o != nil && !IsNil(o.HasRoute) {
		return true
	}

	return false
}

// SetHasRoute gets a reference to the given bool and assigns it to the HasRoute field.
func (o *VisitorDataConditionTraceOption) SetHasRoute(v bool) {
	o.HasRoute = &v
}

// GetMatched returns the Matched field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetMatched() bool {
	if o == nil || IsNil(o.Matched) {
		var ret bool
		return ret
	}
	return *o.Matched
}

// GetMatchedOk returns a tuple with the Matched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetMatchedOk() (*bool, bool) {
	if o == nil || IsNil(o.Matched) {
		return nil, false
	}
	return o.Matched, true
}

// HasMatched returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasMatched() bool {
	if o != nil && !IsNil(o.Matched) {
		return true
	}

	return false
}

// SetMatched gets a reference to the given bool and assigns it to the Matched field.
func (o *VisitorDataConditionTraceOption) SetMatched(v bool) {
	o.Matched = &v
}

// GetObservedValue returns the ObservedValue field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetObservedValue() string {
	if o == nil || IsNil(o.ObservedValue) {
		var ret string
		return ret
	}
	return *o.ObservedValue
}

// GetObservedValueOk returns a tuple with the ObservedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetObservedValueOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedValue) {
		return nil, false
	}
	return o.ObservedValue, true
}

// HasObservedValue returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasObservedValue() bool {
	if o != nil && !IsNil(o.ObservedValue) {
		return true
	}

	return false
}

// SetObservedValue gets a reference to the given string and assigns it to the ObservedValue field.
func (o *VisitorDataConditionTraceOption) SetObservedValue(v string) {
	o.ObservedValue = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *VisitorDataConditionTraceOption) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VisitorDataConditionTraceOption) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *VisitorDataConditionTraceOption) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *VisitorDataConditionTraceOption) SetOperator(v string) {
	o.Operator = &v
}

func (o VisitorDataConditionTraceOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VisitorDataConditionTraceOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeFound) {
		toSerialize["attributeFound"] = o.AttributeFound
	}
	if !IsNil(o.AttributeKey) {
		toSerialize["attributeKey"] = o.AttributeKey
	}
	if !IsNil(o.ComparisonValue) {
		toSerialize["comparisonValue"] = o.ComparisonValue
	}
	if !IsNil(o.HasRoute) {
		toSerialize["hasRoute"] = o.HasRoute
	}
	if !IsNil(o.Matched) {
		toSerialize["matched"] = o.Matched
	}
	if !IsNil(o.ObservedValue) {
		toSerialize["observedValue"] = o.ObservedValue
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	return toSerialize, nil
}

type NullableVisitorDataConditionTraceOption struct {
	value *VisitorDataConditionTraceOption
	isSet bool
}

func (v NullableVisitorDataConditionTraceOption) Get() *VisitorDataConditionTraceOption {
	return v.value
}

func (v *NullableVisitorDataConditionTraceOption) Set(val *VisitorDataConditionTraceOption) {
	v.value = val
	v.isSet = true
}

func (v NullableVisitorDataConditionTraceOption) IsSet() bool {
	return v.isSet
}

func (v *NullableVisitorDataConditionTraceOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVisitorDataConditionTraceOption(val *VisitorDataConditionTraceOption) *NullableVisitorDataConditionTraceOption {
	return &NullableVisitorDataConditionTraceOption{value: val, isSet: true}
}

func (v NullableVisitorDataConditionTraceOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVisitorDataConditionTraceOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


