/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the LeadScoreBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeadScoreBreakdown{}

// LeadScoreBreakdown struct for LeadScoreBreakdown
type LeadScoreBreakdown struct {
	BrandSupportiveness *int32 `json:"brandSupportiveness,omitempty"`
	EngagementLevel *int32 `json:"engagementLevel,omitempty"`
	ProfileFit *int32 `json:"profileFit,omitempty"`
	RecurringInterest *int32 `json:"recurringInterest,omitempty"`
	TechnologicalAptitude *int32 `json:"technologicalAptitude,omitempty"`
}

// NewLeadScoreBreakdown instantiates a new LeadScoreBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeadScoreBreakdown() *LeadScoreBreakdown {
	this := LeadScoreBreakdown{}
	return &this
}

// NewLeadScoreBreakdownWithDefaults instantiates a new LeadScoreBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeadScoreBreakdownWithDefaults() *LeadScoreBreakdown {
	this := LeadScoreBreakdown{}
	return &this
}

// GetBrandSupportiveness returns the BrandSupportiveness field value if set, zero value otherwise.
func (o *LeadScoreBreakdown) GetBrandSupportiveness() int32 {
	if o == nil || IsNil(o.BrandSupportiveness) {
		var ret int32
		return ret
	}
	return *o.BrandSupportiveness
}

// GetBrandSupportivenessOk returns a tuple with the BrandSupportiveness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadScoreBreakdown) GetBrandSupportivenessOk() (*int32, bool) {
	if o == nil || IsNil(o.BrandSupportiveness) {
		return nil, false
	}
	return o.BrandSupportiveness, true
}

// HasBrandSupportiveness returns a boolean if a field has been set.
func (o *LeadScoreBreakdown) HasBrandSupportiveness() bool {
	if o != nil && !IsNil(o.BrandSupportiveness) {
		return true
	}

	return false
}

// SetBrandSupportiveness gets a reference to the given int32 and assigns it to the BrandSupportiveness field.
func (o *LeadScoreBreakdown) SetBrandSupportiveness(v int32) {
	o.BrandSupportiveness = &v
}

// GetEngagementLevel returns the EngagementLevel field value if set, zero value otherwise.
func (o *LeadScoreBreakdown) GetEngagementLevel() int32 {
	if o == nil || IsNil(o.EngagementLevel) {
		var ret int32
		return ret
	}
	return *o.EngagementLevel
}

// GetEngagementLevelOk returns a tuple with the EngagementLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadScoreBreakdown) GetEngagementLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.EngagementLevel) {
		return nil, false
	}
	return o.EngagementLevel, true
}

// HasEngagementLevel returns a boolean if a field has been set.
func (o *LeadScoreBreakdown) HasEngagementLevel() bool {
	if o != nil && !IsNil(o.EngagementLevel) {
		return true
	}

	return false
}

// SetEngagementLevel gets a reference to the given int32 and assigns it to the EngagementLevel field.
func (o *LeadScoreBreakdown) SetEngagementLevel(v int32) {
	o.EngagementLevel = &v
}

// GetProfileFit returns the ProfileFit field value if set, zero value otherwise.
func (o *LeadScoreBreakdown) GetProfileFit() int32 {
	if o == nil || IsNil(o.ProfileFit) {
		var ret int32
		return ret
	}
	return *o.ProfileFit
}

// GetProfileFitOk returns a tuple with the ProfileFit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadScoreBreakdown) GetProfileFitOk() (*int32, bool) {
	if o == nil || IsNil(o.ProfileFit) {
		return nil, false
	}
	return o.ProfileFit, true
}

// HasProfileFit returns a boolean if a field has been set.
func (o *LeadScoreBreakdown) HasProfileFit() bool {
	if o != nil && !IsNil(o.ProfileFit) {
		return true
	}

	return false
}

// SetProfileFit gets a reference to the given int32 and assigns it to the ProfileFit field.
func (o *LeadScoreBreakdown) SetProfileFit(v int32) {
	o.ProfileFit = &v
}

// GetRecurringInterest returns the RecurringInterest field value if set, zero value otherwise.
func (o *LeadScoreBreakdown) GetRecurringInterest() int32 {
	if o == nil || IsNil(o.RecurringInterest) {
		var ret int32
		return ret
	}
	return *o.RecurringInterest
}

// GetRecurringInterestOk returns a tuple with the RecurringInterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadScoreBreakdown) GetRecurringInterestOk() (*int32, bool) {
	if o == nil || IsNil(o.RecurringInterest) {
		return nil, false
	}
	return o.RecurringInterest, true
}

// HasRecurringInterest returns a boolean if a field has been set.
func (o *LeadScoreBreakdown) HasRecurringInterest() bool {
	if o != nil && !IsNil(o.RecurringInterest) {
		return true
	}

	return false
}

// SetRecurringInterest gets a reference to the given int32 and assigns it to the RecurringInterest field.
func (o *LeadScoreBreakdown) SetRecurringInterest(v int32) {
	o.RecurringInterest = &v
}

// GetTechnologicalAptitude returns the TechnologicalAptitude field value if set, zero value otherwise.
func (o *LeadScoreBreakdown) GetTechnologicalAptitude() int32 {
	if o == nil || IsNil(o.TechnologicalAptitude) {
		var ret int32
		return ret
	}
	return *o.TechnologicalAptitude
}

// GetTechnologicalAptitudeOk returns a tuple with the TechnologicalAptitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadScoreBreakdown) GetTechnologicalAptitudeOk() (*int32, bool) {
	if o == nil || IsNil(o.TechnologicalAptitude) {
		return nil, false
	}
	return o.TechnologicalAptitude, true
}

// HasTechnologicalAptitude returns a boolean if a field has been set.
func (o *LeadScoreBreakdown) HasTechnologicalAptitude() bool {
	if o != nil && !IsNil(o.TechnologicalAptitude) {
		return true
	}

	return false
}

// SetTechnologicalAptitude gets a reference to the given int32 and assigns it to the TechnologicalAptitude field.
func (o *LeadScoreBreakdown) SetTechnologicalAptitude(v int32) {
	o.TechnologicalAptitude = &v
}

func (o LeadScoreBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeadScoreBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrandSupportiveness) {
		toSerialize["brandSupportiveness"] = o.BrandSupportiveness
	}
	if !IsNil(o.EngagementLevel) {
		toSerialize["engagementLevel"] = o.EngagementLevel
	}
	if !IsNil(o.ProfileFit) {
		toSerialize["profileFit"] = o.ProfileFit
	}
	if !IsNil(o.RecurringInterest) {
		toSerialize["recurringInterest"] = o.RecurringInterest
	}
	if !IsNil(o.TechnologicalAptitude) {
		toSerialize["technologicalAptitude"] = o.TechnologicalAptitude
	}
	return toSerialize, nil
}

type NullableLeadScoreBreakdown struct {
	value *LeadScoreBreakdown
	isSet bool
}

func (v NullableLeadScoreBreakdown) Get() *LeadScoreBreakdown {
	return v.value
}

func (v *NullableLeadScoreBreakdown) Set(val *LeadScoreBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableLeadScoreBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableLeadScoreBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeadScoreBreakdown(val *LeadScoreBreakdown) *NullableLeadScoreBreakdown {
	return &NullableLeadScoreBreakdown{value: val, isSet: true}
}

func (v NullableLeadScoreBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeadScoreBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


