/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBulkLinksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBulkLinksRequest{}

// CreateBulkLinksRequest Request to create links in bulk.
type CreateBulkLinksRequest struct {
	// Links to create in one batch. Every item supports the same customization fields as CreateLinkRequest.
	Links []CreateLinkRequest `json:"links"`
}

type _CreateBulkLinksRequest CreateBulkLinksRequest

// NewCreateBulkLinksRequest instantiates a new CreateBulkLinksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBulkLinksRequest(links []CreateLinkRequest) *CreateBulkLinksRequest {
	this := CreateBulkLinksRequest{}
	this.Links = links
	return &this
}

// NewCreateBulkLinksRequestWithDefaults instantiates a new CreateBulkLinksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBulkLinksRequestWithDefaults() *CreateBulkLinksRequest {
	this := CreateBulkLinksRequest{}
	return &this
}

// GetLinks returns the Links field value
func (o *CreateBulkLinksRequest) GetLinks() []CreateLinkRequest {
	if o == nil {
		var ret []CreateLinkRequest
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CreateBulkLinksRequest) GetLinksOk() ([]CreateLinkRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *CreateBulkLinksRequest) SetLinks(v []CreateLinkRequest) {
	o.Links = v
}

func (o CreateBulkLinksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBulkLinksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CreateBulkLinksRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBulkLinksRequest := _CreateBulkLinksRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBulkLinksRequest)

	if err != nil {
		return err
	}

	*o = CreateBulkLinksRequest(varCreateBulkLinksRequest)

	return err
}

type NullableCreateBulkLinksRequest struct {
	value *CreateBulkLinksRequest
	isSet bool
}

func (v NullableCreateBulkLinksRequest) Get() *CreateBulkLinksRequest {
	return v.value
}

func (v *NullableCreateBulkLinksRequest) Set(val *CreateBulkLinksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBulkLinksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBulkLinksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBulkLinksRequest(val *CreateBulkLinksRequest) *NullableCreateBulkLinksRequest {
	return &NullableCreateBulkLinksRequest{value: val, isSet: true}
}

func (v NullableCreateBulkLinksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBulkLinksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


