/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.42.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the ImportQrcodeTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportQrcodeTemplateRequest{}

// ImportQrcodeTemplateRequest struct for ImportQrcodeTemplateRequest
type ImportQrcodeTemplateRequest struct {
	// The slug of the public QR code template to import into your workspace
	Slug *string `json:"slug,omitempty"`
}

// NewImportQrcodeTemplateRequest instantiates a new ImportQrcodeTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportQrcodeTemplateRequest() *ImportQrcodeTemplateRequest {
	this := ImportQrcodeTemplateRequest{}
	return &this
}

// NewImportQrcodeTemplateRequestWithDefaults instantiates a new ImportQrcodeTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportQrcodeTemplateRequestWithDefaults() *ImportQrcodeTemplateRequest {
	this := ImportQrcodeTemplateRequest{}
	return &this
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ImportQrcodeTemplateRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportQrcodeTemplateRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ImportQrcodeTemplateRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ImportQrcodeTemplateRequest) SetSlug(v string) {
	o.Slug = &v
}

func (o ImportQrcodeTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportQrcodeTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	return toSerialize, nil
}

type NullableImportQrcodeTemplateRequest struct {
	value *ImportQrcodeTemplateRequest
	isSet bool
}

func (v NullableImportQrcodeTemplateRequest) Get() *ImportQrcodeTemplateRequest {
	return v.value
}

func (v *NullableImportQrcodeTemplateRequest) Set(val *ImportQrcodeTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImportQrcodeTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImportQrcodeTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportQrcodeTemplateRequest(val *ImportQrcodeTemplateRequest) *NullableImportQrcodeTemplateRequest {
	return &NullableImportQrcodeTemplateRequest{value: val, isSet: true}
}

func (v NullableImportQrcodeTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportQrcodeTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


