/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API's name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.

API version: 1.150.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"fmt"
)

// DeviceBrandConditionValue Allowed values for device brand routing conditions.
type DeviceBrandConditionValue string

// List of DeviceBrandConditionValue
const (
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_UNSPECIFIED DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_UNSPECIFIED"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_APPLE DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_APPLE"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_SAMSUNG DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_SAMSUNG"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_GOOGLE DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_GOOGLE"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_HUAWEI DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_HUAWEI"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_XIAOMI DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_XIAOMI"
	DEVICEBRANDCONDITIONVALUE_DEVICE_BRAND_CONDITION_VALUE_ONEPLUS DeviceBrandConditionValue = "DEVICE_BRAND_CONDITION_VALUE_ONEPLUS"
)

// All allowed values of DeviceBrandConditionValue enum
var AllowedDeviceBrandConditionValueEnumValues = []DeviceBrandConditionValue{
	"DEVICE_BRAND_CONDITION_VALUE_UNSPECIFIED",
	"DEVICE_BRAND_CONDITION_VALUE_APPLE",
	"DEVICE_BRAND_CONDITION_VALUE_SAMSUNG",
	"DEVICE_BRAND_CONDITION_VALUE_GOOGLE",
	"DEVICE_BRAND_CONDITION_VALUE_HUAWEI",
	"DEVICE_BRAND_CONDITION_VALUE_XIAOMI",
	"DEVICE_BRAND_CONDITION_VALUE_ONEPLUS",
}

func (v *DeviceBrandConditionValue) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeviceBrandConditionValue(value)
	for _, existing := range AllowedDeviceBrandConditionValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeviceBrandConditionValue", value)
}

// NewDeviceBrandConditionValueFromValue returns a pointer to a valid DeviceBrandConditionValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeviceBrandConditionValueFromValue(v string) (*DeviceBrandConditionValue, error) {
	ev := DeviceBrandConditionValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeviceBrandConditionValue: valid values are %v", v, AllowedDeviceBrandConditionValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeviceBrandConditionValue) IsValid() bool {
	for _, existing := range AllowedDeviceBrandConditionValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DeviceBrandConditionValue value
func (v DeviceBrandConditionValue) Ptr() *DeviceBrandConditionValue {
	return &v
}

type NullableDeviceBrandConditionValue struct {
	value *DeviceBrandConditionValue
	isSet bool
}

func (v NullableDeviceBrandConditionValue) Get() *DeviceBrandConditionValue {
	return v.value
}

func (v *NullableDeviceBrandConditionValue) Set(val *DeviceBrandConditionValue) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceBrandConditionValue) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceBrandConditionValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceBrandConditionValue(val *DeviceBrandConditionValue) *NullableDeviceBrandConditionValue {
	return &NullableDeviceBrandConditionValue{value: val, isSet: true}
}

func (v NullableDeviceBrandConditionValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceBrandConditionValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

