/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.85.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the AISendMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AISendMessageResponse{}

// AISendMessageResponse struct for AISendMessageResponse
type AISendMessageResponse struct {
	AppliedActions []string `json:"appliedActions,omitempty"`
	ContextUpdated *bool `json:"contextUpdated,omitempty"`
	ResponseText *string `json:"responseText,omitempty"`
	UiActions []ChatUIAction `json:"uiActions,omitempty"`
}

// NewAISendMessageResponse instantiates a new AISendMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAISendMessageResponse() *AISendMessageResponse {
	this := AISendMessageResponse{}
	return &this
}

// NewAISendMessageResponseWithDefaults instantiates a new AISendMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAISendMessageResponseWithDefaults() *AISendMessageResponse {
	this := AISendMessageResponse{}
	return &this
}

// GetAppliedActions returns the AppliedActions field value if set, zero value otherwise.
func (o *AISendMessageResponse) GetAppliedActions() []string {
	if o == nil || IsNil(o.AppliedActions) {
		var ret []string
		return ret
	}
	return o.AppliedActions
}

// GetAppliedActionsOk returns a tuple with the AppliedActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AISendMessageResponse) GetAppliedActionsOk() ([]string, bool) {
	if o == nil || IsNil(o.AppliedActions) {
		return nil, false
	}
	return o.AppliedActions, true
}

// HasAppliedActions returns a boolean if a field has been set.
func (o *AISendMessageResponse) HasAppliedActions() bool {
	if o != nil && !IsNil(o.AppliedActions) {
		return true
	}

	return false
}

// SetAppliedActions gets a reference to the given []string and assigns it to the AppliedActions field.
func (o *AISendMessageResponse) SetAppliedActions(v []string) {
	o.AppliedActions = v
}

// GetContextUpdated returns the ContextUpdated field value if set, zero value otherwise.
func (o *AISendMessageResponse) GetContextUpdated() bool {
	if o == nil || IsNil(o.ContextUpdated) {
		var ret bool
		return ret
	}
	return *o.ContextUpdated
}

// GetContextUpdatedOk returns a tuple with the ContextUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AISendMessageResponse) GetContextUpdatedOk() (*bool, bool) {
	if o == nil || IsNil(o.ContextUpdated) {
		return nil, false
	}
	return o.ContextUpdated, true
}

// HasContextUpdated returns a boolean if a field has been set.
func (o *AISendMessageResponse) HasContextUpdated() bool {
	if o != nil && !IsNil(o.ContextUpdated) {
		return true
	}

	return false
}

// SetContextUpdated gets a reference to the given bool and assigns it to the ContextUpdated field.
func (o *AISendMessageResponse) SetContextUpdated(v bool) {
	o.ContextUpdated = &v
}

// GetResponseText returns the ResponseText field value if set, zero value otherwise.
func (o *AISendMessageResponse) GetResponseText() string {
	if o == nil || IsNil(o.ResponseText) {
		var ret string
		return ret
	}
	return *o.ResponseText
}

// GetResponseTextOk returns a tuple with the ResponseText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AISendMessageResponse) GetResponseTextOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseText) {
		return nil, false
	}
	return o.ResponseText, true
}

// HasResponseText returns a boolean if a field has been set.
func (o *AISendMessageResponse) HasResponseText() bool {
	if o != nil && !IsNil(o.ResponseText) {
		return true
	}

	return false
}

// SetResponseText gets a reference to the given string and assigns it to the ResponseText field.
func (o *AISendMessageResponse) SetResponseText(v string) {
	o.ResponseText = &v
}

// GetUiActions returns the UiActions field value if set, zero value otherwise.
func (o *AISendMessageResponse) GetUiActions() []ChatUIAction {
	if o == nil || IsNil(o.UiActions) {
		var ret []ChatUIAction
		return ret
	}
	return o.UiActions
}

// GetUiActionsOk returns a tuple with the UiActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AISendMessageResponse) GetUiActionsOk() ([]ChatUIAction, bool) {
	if o == nil || IsNil(o.UiActions) {
		return nil, false
	}
	return o.UiActions, true
}

// HasUiActions returns a boolean if a field has been set.
func (o *AISendMessageResponse) HasUiActions() bool {
	if o != nil && !IsNil(o.UiActions) {
		return true
	}

	return false
}

// SetUiActions gets a reference to the given []ChatUIAction and assigns it to the UiActions field.
func (o *AISendMessageResponse) SetUiActions(v []ChatUIAction) {
	o.UiActions = v
}

func (o AISendMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AISendMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppliedActions) {
		toSerialize["appliedActions"] = o.AppliedActions
	}
	if !IsNil(o.ContextUpdated) {
		toSerialize["contextUpdated"] = o.ContextUpdated
	}
	if !IsNil(o.ResponseText) {
		toSerialize["responseText"] = o.ResponseText
	}
	if !IsNil(o.UiActions) {
		toSerialize["uiActions"] = o.UiActions
	}
	return toSerialize, nil
}

type NullableAISendMessageResponse struct {
	value *AISendMessageResponse
	isSet bool
}

func (v NullableAISendMessageResponse) Get() *AISendMessageResponse {
	return v.value
}

func (v *NullableAISendMessageResponse) Set(val *AISendMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAISendMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAISendMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAISendMessageResponse(val *AISendMessageResponse) *NullableAISendMessageResponse {
	return &NullableAISendMessageResponse{value: val, isSet: true}
}

func (v NullableAISendMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAISendMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


