/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the MultiLinkTraceButton type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiLinkTraceButton{}

// MultiLinkTraceButton MultiLinkTraceButton stores metadata for all buttons available on the multi-link page.
type MultiLinkTraceButton struct {
	Id *string `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
	Order *int32 `json:"order,omitempty"`
}

// NewMultiLinkTraceButton instantiates a new MultiLinkTraceButton object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiLinkTraceButton() *MultiLinkTraceButton {
	this := MultiLinkTraceButton{}
	return &this
}

// NewMultiLinkTraceButtonWithDefaults instantiates a new MultiLinkTraceButton object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiLinkTraceButtonWithDefaults() *MultiLinkTraceButton {
	this := MultiLinkTraceButton{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MultiLinkTraceButton) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiLinkTraceButton) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MultiLinkTraceButton) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MultiLinkTraceButton) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *MultiLinkTraceButton) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiLinkTraceButton) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *MultiLinkTraceButton) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *MultiLinkTraceButton) SetLabel(v string) {
	o.Label = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *MultiLinkTraceButton) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiLinkTraceButton) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *MultiLinkTraceButton) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *MultiLinkTraceButton) SetOrder(v int32) {
	o.Order = &v
}

func (o MultiLinkTraceButton) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiLinkTraceButton) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableMultiLinkTraceButton struct {
	value *MultiLinkTraceButton
	isSet bool
}

func (v NullableMultiLinkTraceButton) Get() *MultiLinkTraceButton {
	return v.value
}

func (v *NullableMultiLinkTraceButton) Set(val *MultiLinkTraceButton) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiLinkTraceButton) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiLinkTraceButton) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiLinkTraceButton(val *MultiLinkTraceButton) *NullableMultiLinkTraceButton {
	return &NullableMultiLinkTraceButton{value: val, isSet: true}
}

func (v NullableMultiLinkTraceButton) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiLinkTraceButton) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


