/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.77.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the HourOfDayDataPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HourOfDayDataPoint{}

// HourOfDayDataPoint struct for HourOfDayDataPoint
type HourOfDayDataPoint struct {
	EventCount *int32 `json:"eventCount,omitempty"`
	Hour *int32 `json:"hour,omitempty"`
}

// NewHourOfDayDataPoint instantiates a new HourOfDayDataPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHourOfDayDataPoint() *HourOfDayDataPoint {
	this := HourOfDayDataPoint{}
	return &this
}

// NewHourOfDayDataPointWithDefaults instantiates a new HourOfDayDataPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHourOfDayDataPointWithDefaults() *HourOfDayDataPoint {
	this := HourOfDayDataPoint{}
	return &this
}

// GetEventCount returns the EventCount field value if set, zero value otherwise.
func (o *HourOfDayDataPoint) GetEventCount() int32 {
	if o == nil || IsNil(o.EventCount) {
		var ret int32
		return ret
	}
	return *o.EventCount
}

// GetEventCountOk returns a tuple with the EventCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HourOfDayDataPoint) GetEventCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EventCount) {
		return nil, false
	}
	return o.EventCount, true
}

// HasEventCount returns a boolean if a field has been set.
func (o *HourOfDayDataPoint) HasEventCount() bool {
	if o != nil && !IsNil(o.EventCount) {
		return true
	}

	return false
}

// SetEventCount gets a reference to the given int32 and assigns it to the EventCount field.
func (o *HourOfDayDataPoint) SetEventCount(v int32) {
	o.EventCount = &v
}

// GetHour returns the Hour field value if set, zero value otherwise.
func (o *HourOfDayDataPoint) GetHour() int32 {
	if o == nil || IsNil(o.Hour) {
		var ret int32
		return ret
	}
	return *o.Hour
}

// GetHourOk returns a tuple with the Hour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HourOfDayDataPoint) GetHourOk() (*int32, bool) {
	if o == nil || IsNil(o.Hour) {
		return nil, false
	}
	return o.Hour, true
}

// HasHour returns a boolean if a field has been set.
func (o *HourOfDayDataPoint) HasHour() bool {
	if o != nil && !IsNil(o.Hour) {
		return true
	}

	return false
}

// SetHour gets a reference to the given int32 and assigns it to the Hour field.
func (o *HourOfDayDataPoint) SetHour(v int32) {
	o.Hour = &v
}

func (o HourOfDayDataPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HourOfDayDataPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventCount) {
		toSerialize["eventCount"] = o.EventCount
	}
	if !IsNil(o.Hour) {
		toSerialize["hour"] = o.Hour
	}
	return toSerialize, nil
}

type NullableHourOfDayDataPoint struct {
	value *HourOfDayDataPoint
	isSet bool
}

func (v NullableHourOfDayDataPoint) Get() *HourOfDayDataPoint {
	return v.value
}

func (v *NullableHourOfDayDataPoint) Set(val *HourOfDayDataPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableHourOfDayDataPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableHourOfDayDataPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHourOfDayDataPoint(val *HourOfDayDataPoint) *NullableHourOfDayDataPoint {
	return &NullableHourOfDayDataPoint{value: val, isSet: true}
}

func (v NullableHourOfDayDataPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHourOfDayDataPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


