/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.144.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the SocketPongMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocketPongMessage{}

// SocketPongMessage SocketPongMessage answers a ping.
type SocketPongMessage struct {
	Type *SocketMessageType `json:"type,omitempty"`
}

// NewSocketPongMessage instantiates a new SocketPongMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocketPongMessage() *SocketPongMessage {
	this := SocketPongMessage{}
	var type_ SocketMessageType = SOCKETMESSAGETYPE_SOCKET_MESSAGE_TYPE_UNSPECIFIED
	this.Type = &type_
	return &this
}

// NewSocketPongMessageWithDefaults instantiates a new SocketPongMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocketPongMessageWithDefaults() *SocketPongMessage {
	this := SocketPongMessage{}
	var type_ SocketMessageType = SOCKETMESSAGETYPE_SOCKET_MESSAGE_TYPE_UNSPECIFIED
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SocketPongMessage) GetType() SocketMessageType {
	if o == nil || IsNil(o.Type) {
		var ret SocketMessageType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocketPongMessage) GetTypeOk() (*SocketMessageType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SocketPongMessage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given SocketMessageType and assigns it to the Type field.
func (o *SocketPongMessage) SetType(v SocketMessageType) {
	o.Type = &v
}

func (o SocketPongMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocketPongMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSocketPongMessage struct {
	value *SocketPongMessage
	isSet bool
}

func (v NullableSocketPongMessage) Get() *SocketPongMessage {
	return v.value
}

func (v *NullableSocketPongMessage) Set(val *SocketPongMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSocketPongMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSocketPongMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocketPongMessage(val *SocketPongMessage) *NullableSocketPongMessage {
	return &NullableSocketPongMessage{value: val, isSet: true}
}

func (v NullableSocketPongMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocketPongMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


