/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.115.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the WorkflowStepBranch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStepBranch{}

// WorkflowStepBranch One exit of a workflow step. Server-derived, returned on every step read.
type WorkflowStepBranch struct {
	// The id this branch is addressed by: \"next\" for an atomic step's single exit, \"else\" for a condition's fallback, or the id the branch carries in the step's payload — a button id, option id, range id, or country code.
	BranchId *string `json:"branchId,omitempty"`
	// Human-readable name of the branch: a button's label, a country code, a condition option's name, \"fallback\", \"next step\".
	Label *string `json:"label,omitempty"`
	// The step this branch leads to. Empty when the branch is unconnected.
	NextStepId *string `json:"nextStepId,omitempty"`
}

// NewWorkflowStepBranch instantiates a new WorkflowStepBranch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStepBranch() *WorkflowStepBranch {
	this := WorkflowStepBranch{}
	return &this
}

// NewWorkflowStepBranchWithDefaults instantiates a new WorkflowStepBranch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepBranchWithDefaults() *WorkflowStepBranch {
	this := WorkflowStepBranch{}
	return &this
}

// GetBranchId returns the BranchId field value if set, zero value otherwise.
func (o *WorkflowStepBranch) GetBranchId() string {
	if o == nil || IsNil(o.BranchId) {
		var ret string
		return ret
	}
	return *o.BranchId
}

// GetBranchIdOk returns a tuple with the BranchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepBranch) GetBranchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BranchId) {
		return nil, false
	}
	return o.BranchId, true
}

// HasBranchId returns a boolean if a field has been set.
func (o *WorkflowStepBranch) HasBranchId() bool {
	if o != nil && !IsNil(o.BranchId) {
		return true
	}

	return false
}

// SetBranchId gets a reference to the given string and assigns it to the BranchId field.
func (o *WorkflowStepBranch) SetBranchId(v string) {
	o.BranchId = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *WorkflowStepBranch) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepBranch) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *WorkflowStepBranch) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *WorkflowStepBranch) SetLabel(v string) {
	o.Label = &v
}

// GetNextStepId returns the NextStepId field value if set, zero value otherwise.
func (o *WorkflowStepBranch) GetNextStepId() string {
	if o == nil || IsNil(o.NextStepId) {
		var ret string
		return ret
	}
	return *o.NextStepId
}

// GetNextStepIdOk returns a tuple with the NextStepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStepBranch) GetNextStepIdOk() (*string, bool) {
	if o == nil || IsNil(o.NextStepId) {
		return nil, false
	}
	return o.NextStepId, true
}

// HasNextStepId returns a boolean if a field has been set.
func (o *WorkflowStepBranch) HasNextStepId() bool {
	if o != nil && !IsNil(o.NextStepId) {
		return true
	}

	return false
}

// SetNextStepId gets a reference to the given string and assigns it to the NextStepId field.
func (o *WorkflowStepBranch) SetNextStepId(v string) {
	o.NextStepId = &v
}

func (o WorkflowStepBranch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStepBranch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BranchId) {
		toSerialize["branchId"] = o.BranchId
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.NextStepId) {
		toSerialize["nextStepId"] = o.NextStepId
	}
	return toSerialize, nil
}

type NullableWorkflowStepBranch struct {
	value *WorkflowStepBranch
	isSet bool
}

func (v NullableWorkflowStepBranch) Get() *WorkflowStepBranch {
	return v.value
}

func (v *NullableWorkflowStepBranch) Set(val *WorkflowStepBranch) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStepBranch) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStepBranch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStepBranch(val *WorkflowStepBranch) *NullableWorkflowStepBranch {
	return &NullableWorkflowStepBranch{value: val, isSet: true}
}

func (v NullableWorkflowStepBranch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStepBranch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


