/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the DayOfMonthConditionTraceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DayOfMonthConditionTraceData{}

// DayOfMonthConditionTraceData DayOfMonthConditionTraceData stores day-of-month condition routing metadata.
type DayOfMonthConditionTraceData struct {
	HasElse *bool `json:"hasElse,omitempty"`
	Options []DayOfMonthConditionTraceOption `json:"options,omitempty"`
}

// NewDayOfMonthConditionTraceData instantiates a new DayOfMonthConditionTraceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDayOfMonthConditionTraceData() *DayOfMonthConditionTraceData {
	this := DayOfMonthConditionTraceData{}
	return &this
}

// NewDayOfMonthConditionTraceDataWithDefaults instantiates a new DayOfMonthConditionTraceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDayOfMonthConditionTraceDataWithDefaults() *DayOfMonthConditionTraceData {
	this := DayOfMonthConditionTraceData{}
	return &this
}

// GetHasElse returns the HasElse field value if set, zero value otherwise.
func (o *DayOfMonthConditionTraceData) GetHasElse() bool {
	if o == nil || IsNil(o.HasElse) {
		var ret bool
		return ret
	}
	return *o.HasElse
}

// GetHasElseOk returns a tuple with the HasElse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DayOfMonthConditionTraceData) GetHasElseOk() (*bool, bool) {
	if o == nil || IsNil(o.HasElse) {
		return nil, false
	}
	return o.HasElse, true
}

// HasHasElse returns a boolean if a field has been set.
func (o *DayOfMonthConditionTraceData) HasHasElse() bool {
	if o != nil && !IsNil(o.HasElse) {
		return true
	}

	return false
}

// SetHasElse gets a reference to the given bool and assigns it to the HasElse field.
func (o *DayOfMonthConditionTraceData) SetHasElse(v bool) {
	o.HasElse = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *DayOfMonthConditionTraceData) GetOptions() []DayOfMonthConditionTraceOption {
	if o == nil || IsNil(o.Options) {
		var ret []DayOfMonthConditionTraceOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DayOfMonthConditionTraceData) GetOptionsOk() ([]DayOfMonthConditionTraceOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *DayOfMonthConditionTraceData) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []DayOfMonthConditionTraceOption and assigns it to the Options field.
func (o *DayOfMonthConditionTraceData) SetOptions(v []DayOfMonthConditionTraceOption) {
	o.Options = v
}

func (o DayOfMonthConditionTraceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DayOfMonthConditionTraceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasElse) {
		toSerialize["hasElse"] = o.HasElse
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableDayOfMonthConditionTraceData struct {
	value *DayOfMonthConditionTraceData
	isSet bool
}

func (v NullableDayOfMonthConditionTraceData) Get() *DayOfMonthConditionTraceData {
	return v.value
}

func (v *NullableDayOfMonthConditionTraceData) Set(val *DayOfMonthConditionTraceData) {
	v.value = val
	v.isSet = true
}

func (v NullableDayOfMonthConditionTraceData) IsSet() bool {
	return v.isSet
}

func (v *NullableDayOfMonthConditionTraceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDayOfMonthConditionTraceData(val *DayOfMonthConditionTraceData) *NullableDayOfMonthConditionTraceData {
	return &NullableDayOfMonthConditionTraceData{value: val, isSet: true}
}

func (v NullableDayOfMonthConditionTraceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDayOfMonthConditionTraceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


