/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.87.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessagePagePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessagePagePayload{}

// MessagePagePayload struct for MessagePagePayload
type MessagePagePayload struct {
	ButtonLabel *string `json:"buttonLabel,omitempty"`
	Description *string `json:"description,omitempty"`
	NavigationType MessagePageNavigationType `json:"navigationType"`
	TimerSeconds *int32 `json:"timerSeconds,omitempty"`
	Title string `json:"title"`
}

type _MessagePagePayload MessagePagePayload

// NewMessagePagePayload instantiates a new MessagePagePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessagePagePayload(navigationType MessagePageNavigationType, title string) *MessagePagePayload {
	this := MessagePagePayload{}
	this.NavigationType = navigationType
	this.Title = title
	return &this
}

// NewMessagePagePayloadWithDefaults instantiates a new MessagePagePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessagePagePayloadWithDefaults() *MessagePagePayload {
	this := MessagePagePayload{}
	return &this
}

// GetButtonLabel returns the ButtonLabel field value if set, zero value otherwise.
func (o *MessagePagePayload) GetButtonLabel() string {
	if o == nil || IsNil(o.ButtonLabel) {
		var ret string
		return ret
	}
	return *o.ButtonLabel
}

// GetButtonLabelOk returns a tuple with the ButtonLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessagePagePayload) GetButtonLabelOk() (*string, bool) {
	if o == nil || IsNil(o.ButtonLabel) {
		return nil, false
	}
	return o.ButtonLabel, true
}

// HasButtonLabel returns a boolean if a field has been set.
func (o *MessagePagePayload) HasButtonLabel() bool {
	if o != nil && !IsNil(o.ButtonLabel) {
		return true
	}

	return false
}

// SetButtonLabel gets a reference to the given string and assigns it to the ButtonLabel field.
func (o *MessagePagePayload) SetButtonLabel(v string) {
	o.ButtonLabel = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MessagePagePayload) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessagePagePayload) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MessagePagePayload) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MessagePagePayload) SetDescription(v string) {
	o.Description = &v
}

// GetNavigationType returns the NavigationType field value
func (o *MessagePagePayload) GetNavigationType() MessagePageNavigationType {
	if o == nil {
		var ret MessagePageNavigationType
		return ret
	}

	return o.NavigationType
}

// GetNavigationTypeOk returns a tuple with the NavigationType field value
// and a boolean to check if the value has been set.
func (o *MessagePagePayload) GetNavigationTypeOk() (*MessagePageNavigationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NavigationType, true
}

// SetNavigationType sets field value
func (o *MessagePagePayload) SetNavigationType(v MessagePageNavigationType) {
	o.NavigationType = v
}

// GetTimerSeconds returns the TimerSeconds field value if set, zero value otherwise.
func (o *MessagePagePayload) GetTimerSeconds() int32 {
	if o == nil || IsNil(o.TimerSeconds) {
		var ret int32
		return ret
	}
	return *o.TimerSeconds
}

// GetTimerSecondsOk returns a tuple with the TimerSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessagePagePayload) GetTimerSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimerSeconds) {
		return nil, false
	}
	return o.TimerSeconds, true
}

// HasTimerSeconds returns a boolean if a field has been set.
func (o *MessagePagePayload) HasTimerSeconds() bool {
	if o != nil && !IsNil(o.TimerSeconds) {
		return true
	}

	return false
}

// SetTimerSeconds gets a reference to the given int32 and assigns it to the TimerSeconds field.
func (o *MessagePagePayload) SetTimerSeconds(v int32) {
	o.TimerSeconds = &v
}

// GetTitle returns the Title field value
func (o *MessagePagePayload) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MessagePagePayload) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MessagePagePayload) SetTitle(v string) {
	o.Title = v
}

func (o MessagePagePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessagePagePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ButtonLabel) {
		toSerialize["buttonLabel"] = o.ButtonLabel
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["navigationType"] = o.NavigationType
	if !IsNil(o.TimerSeconds) {
		toSerialize["timerSeconds"] = o.TimerSeconds
	}
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *MessagePagePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"navigationType",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessagePagePayload := _MessagePagePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessagePagePayload)

	if err != nil {
		return err
	}

	*o = MessagePagePayload(varMessagePagePayload)

	return err
}

type NullableMessagePagePayload struct {
	value *MessagePagePayload
	isSet bool
}

func (v NullableMessagePagePayload) Get() *MessagePagePayload {
	return v.value
}

func (v *NullableMessagePagePayload) Set(val *MessagePagePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMessagePagePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMessagePagePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessagePagePayload(val *MessagePagePayload) *NullableMessagePagePayload {
	return &NullableMessagePagePayload{value: val, isSet: true}
}

func (v NullableMessagePagePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessagePagePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


