/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
	"time"
)

// checks if the GetEventsTimeSeriesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEventsTimeSeriesRequest{}

// GetEventsTimeSeriesRequest struct for GetEventsTimeSeriesRequest
type GetEventsTimeSeriesRequest struct {
	EndDate *time.Time `json:"endDate,omitempty"`
	IntervalInMinutes *int32 `json:"intervalInMinutes,omitempty"`
	// Optional filtering by link ID
	LinkId *string `json:"linkId,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
}

// NewGetEventsTimeSeriesRequest instantiates a new GetEventsTimeSeriesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEventsTimeSeriesRequest() *GetEventsTimeSeriesRequest {
	this := GetEventsTimeSeriesRequest{}
	return &this
}

// NewGetEventsTimeSeriesRequestWithDefaults instantiates a new GetEventsTimeSeriesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEventsTimeSeriesRequestWithDefaults() *GetEventsTimeSeriesRequest {
	this := GetEventsTimeSeriesRequest{}
	return &this
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetEventsTimeSeriesRequest) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsTimeSeriesRequest) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetEventsTimeSeriesRequest) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *GetEventsTimeSeriesRequest) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetIntervalInMinutes returns the IntervalInMinutes field value if set, zero value otherwise.
func (o *GetEventsTimeSeriesRequest) GetIntervalInMinutes() int32 {
	if o == nil || IsNil(o.IntervalInMinutes) {
		var ret int32
		return ret
	}
	return *o.IntervalInMinutes
}

// GetIntervalInMinutesOk returns a tuple with the IntervalInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsTimeSeriesRequest) GetIntervalInMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalInMinutes) {
		return nil, false
	}
	return o.IntervalInMinutes, true
}

// HasIntervalInMinutes returns a boolean if a field has been set.
func (o *GetEventsTimeSeriesRequest) HasIntervalInMinutes() bool {
	if o != nil && !IsNil(o.IntervalInMinutes) {
		return true
	}

	return false
}

// SetIntervalInMinutes gets a reference to the given int32 and assigns it to the IntervalInMinutes field.
func (o *GetEventsTimeSeriesRequest) SetIntervalInMinutes(v int32) {
	o.IntervalInMinutes = &v
}

// GetLinkId returns the LinkId field value if set, zero value otherwise.
func (o *GetEventsTimeSeriesRequest) GetLinkId() string {
	if o == nil || IsNil(o.LinkId) {
		var ret string
		return ret
	}
	return *o.LinkId
}

// GetLinkIdOk returns a tuple with the LinkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsTimeSeriesRequest) GetLinkIdOk() (*string, bool) {
	if o == nil || IsNil(o.LinkId) {
		return nil, false
	}
	return o.LinkId, true
}

// HasLinkId returns a boolean if a field has been set.
func (o *GetEventsTimeSeriesRequest) HasLinkId() bool {
	if o != nil && !IsNil(o.LinkId) {
		return true
	}

	return false
}

// SetLinkId gets a reference to the given string and assigns it to the LinkId field.
func (o *GetEventsTimeSeriesRequest) SetLinkId(v string) {
	o.LinkId = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetEventsTimeSeriesRequest) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsTimeSeriesRequest) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetEventsTimeSeriesRequest) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *GetEventsTimeSeriesRequest) SetStartDate(v time.Time) {
	o.StartDate = &v
}

func (o GetEventsTimeSeriesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEventsTimeSeriesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.IntervalInMinutes) {
		toSerialize["intervalInMinutes"] = o.IntervalInMinutes
	}
	if !IsNil(o.LinkId) {
		toSerialize["linkId"] = o.LinkId
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	return toSerialize, nil
}

type NullableGetEventsTimeSeriesRequest struct {
	value *GetEventsTimeSeriesRequest
	isSet bool
}

func (v NullableGetEventsTimeSeriesRequest) Get() *GetEventsTimeSeriesRequest {
	return v.value
}

func (v *NullableGetEventsTimeSeriesRequest) Set(val *GetEventsTimeSeriesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventsTimeSeriesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventsTimeSeriesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventsTimeSeriesRequest(val *GetEventsTimeSeriesRequest) *NullableGetEventsTimeSeriesRequest {
	return &NullableGetEventsTimeSeriesRequest{value: val, isSet: true}
}

func (v NullableGetEventsTimeSeriesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventsTimeSeriesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


