/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.147.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the CreditTopup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditTopup{}

// CreditTopup struct for CreditTopup
type CreditTopup struct {
	Amounts []Money `json:"amounts,omitempty"`
	CreditsPerUnit *int32 `json:"creditsPerUnit,omitempty"`
}

// NewCreditTopup instantiates a new CreditTopup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditTopup() *CreditTopup {
	this := CreditTopup{}
	return &this
}

// NewCreditTopupWithDefaults instantiates a new CreditTopup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditTopupWithDefaults() *CreditTopup {
	this := CreditTopup{}
	return &this
}

// GetAmounts returns the Amounts field value if set, zero value otherwise.
func (o *CreditTopup) GetAmounts() []Money {
	if o == nil || IsNil(o.Amounts) {
		var ret []Money
		return ret
	}
	return o.Amounts
}

// GetAmountsOk returns a tuple with the Amounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopup) GetAmountsOk() ([]Money, bool) {
	if o == nil || IsNil(o.Amounts) {
		return nil, false
	}
	return o.Amounts, true
}

// HasAmounts returns a boolean if a field has been set.
func (o *CreditTopup) HasAmounts() bool {
	if o != nil && !IsNil(o.Amounts) {
		return true
	}

	return false
}

// SetAmounts gets a reference to the given []Money and assigns it to the Amounts field.
func (o *CreditTopup) SetAmounts(v []Money) {
	o.Amounts = v
}

// GetCreditsPerUnit returns the CreditsPerUnit field value if set, zero value otherwise.
func (o *CreditTopup) GetCreditsPerUnit() int32 {
	if o == nil || IsNil(o.CreditsPerUnit) {
		var ret int32
		return ret
	}
	return *o.CreditsPerUnit
}

// GetCreditsPerUnitOk returns a tuple with the CreditsPerUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditTopup) GetCreditsPerUnitOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsPerUnit) {
		return nil, false
	}
	return o.CreditsPerUnit, true
}

// HasCreditsPerUnit returns a boolean if a field has been set.
func (o *CreditTopup) HasCreditsPerUnit() bool {
	if o != nil && !IsNil(o.CreditsPerUnit) {
		return true
	}

	return false
}

// SetCreditsPerUnit gets a reference to the given int32 and assigns it to the CreditsPerUnit field.
func (o *CreditTopup) SetCreditsPerUnit(v int32) {
	o.CreditsPerUnit = &v
}

func (o CreditTopup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditTopup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amounts) {
		toSerialize["amounts"] = o.Amounts
	}
	if !IsNil(o.CreditsPerUnit) {
		toSerialize["creditsPerUnit"] = o.CreditsPerUnit
	}
	return toSerialize, nil
}

type NullableCreditTopup struct {
	value *CreditTopup
	isSet bool
}

func (v NullableCreditTopup) Get() *CreditTopup {
	return v.value
}

func (v *NullableCreditTopup) Set(val *CreditTopup) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditTopup) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditTopup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditTopup(val *CreditTopup) *NullableCreditTopup {
	return &NullableCreditTopup{value: val, isSet: true}
}

func (v NullableCreditTopup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditTopup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


