/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.45.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the GetMediaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMediaResponse{}

// GetMediaResponse struct for GetMediaResponse
type GetMediaResponse struct {
	Media *Media `json:"media,omitempty"`
}

// NewGetMediaResponse instantiates a new GetMediaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaResponse() *GetMediaResponse {
	this := GetMediaResponse{}
	return &this
}

// NewGetMediaResponseWithDefaults instantiates a new GetMediaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaResponseWithDefaults() *GetMediaResponse {
	this := GetMediaResponse{}
	return &this
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *GetMediaResponse) GetMedia() Media {
	if o == nil || IsNil(o.Media) {
		var ret Media
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaResponse) GetMediaOk() (*Media, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *GetMediaResponse) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given Media and assigns it to the Media field.
func (o *GetMediaResponse) SetMedia(v Media) {
	o.Media = &v
}

func (o GetMediaResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMediaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	return toSerialize, nil
}

type NullableGetMediaResponse struct {
	value *GetMediaResponse
	isSet bool
}

func (v NullableGetMediaResponse) Get() *GetMediaResponse {
	return v.value
}

func (v *NullableGetMediaResponse) Set(val *GetMediaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaResponse(val *GetMediaResponse) *NullableGetMediaResponse {
	return &NullableGetMediaResponse{value: val, isSet: true}
}

func (v NullableGetMediaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMediaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


