/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.46.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the CreateWorkflowStepResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowStepResponse{}

// CreateWorkflowStepResponse struct for CreateWorkflowStepResponse
type CreateWorkflowStepResponse struct {
	WorkflowStep *WorkflowStep `json:"workflowStep,omitempty"`
}

// NewCreateWorkflowStepResponse instantiates a new CreateWorkflowStepResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowStepResponse() *CreateWorkflowStepResponse {
	this := CreateWorkflowStepResponse{}
	return &this
}

// NewCreateWorkflowStepResponseWithDefaults instantiates a new CreateWorkflowStepResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowStepResponseWithDefaults() *CreateWorkflowStepResponse {
	this := CreateWorkflowStepResponse{}
	return &this
}

// GetWorkflowStep returns the WorkflowStep field value if set, zero value otherwise.
func (o *CreateWorkflowStepResponse) GetWorkflowStep() WorkflowStep {
	if o == nil || IsNil(o.WorkflowStep) {
		var ret WorkflowStep
		return ret
	}
	return *o.WorkflowStep
}

// GetWorkflowStepOk returns a tuple with the WorkflowStep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowStepResponse) GetWorkflowStepOk() (*WorkflowStep, bool) {
	if o == nil || IsNil(o.WorkflowStep) {
		return nil, false
	}
	return o.WorkflowStep, true
}

// HasWorkflowStep returns a boolean if a field has been set.
func (o *CreateWorkflowStepResponse) HasWorkflowStep() bool {
	if o != nil && !IsNil(o.WorkflowStep) {
		return true
	}

	return false
}

// SetWorkflowStep gets a reference to the given WorkflowStep and assigns it to the WorkflowStep field.
func (o *CreateWorkflowStepResponse) SetWorkflowStep(v WorkflowStep) {
	o.WorkflowStep = &v
}

func (o CreateWorkflowStepResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowStepResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WorkflowStep) {
		toSerialize["workflowStep"] = o.WorkflowStep
	}
	return toSerialize, nil
}

type NullableCreateWorkflowStepResponse struct {
	value *CreateWorkflowStepResponse
	isSet bool
}

func (v NullableCreateWorkflowStepResponse) Get() *CreateWorkflowStepResponse {
	return v.value
}

func (v *NullableCreateWorkflowStepResponse) Set(val *CreateWorkflowStepResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowStepResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowStepResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowStepResponse(val *CreateWorkflowStepResponse) *NullableCreateWorkflowStepResponse {
	return &NullableCreateWorkflowStepResponse{value: val, isSet: true}
}

func (v NullableCreateWorkflowStepResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowStepResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


