/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.111.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the GetWidgetSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWidgetSummaryResponse{}

// GetWidgetSummaryResponse struct for GetWidgetSummaryResponse
type GetWidgetSummaryResponse struct {
	Result *AnalyticsWidgetResult `json:"result,omitempty"`
}

// NewGetWidgetSummaryResponse instantiates a new GetWidgetSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWidgetSummaryResponse() *GetWidgetSummaryResponse {
	this := GetWidgetSummaryResponse{}
	return &this
}

// NewGetWidgetSummaryResponseWithDefaults instantiates a new GetWidgetSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWidgetSummaryResponseWithDefaults() *GetWidgetSummaryResponse {
	this := GetWidgetSummaryResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetWidgetSummaryResponse) GetResult() AnalyticsWidgetResult {
	if o == nil || IsNil(o.Result) {
		var ret AnalyticsWidgetResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWidgetSummaryResponse) GetResultOk() (*AnalyticsWidgetResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetWidgetSummaryResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given AnalyticsWidgetResult and assigns it to the Result field.
func (o *GetWidgetSummaryResponse) SetResult(v AnalyticsWidgetResult) {
	o.Result = &v
}

func (o GetWidgetSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWidgetSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableGetWidgetSummaryResponse struct {
	value *GetWidgetSummaryResponse
	isSet bool
}

func (v NullableGetWidgetSummaryResponse) Get() *GetWidgetSummaryResponse {
	return v.value
}

func (v *NullableGetWidgetSummaryResponse) Set(val *GetWidgetSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWidgetSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWidgetSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWidgetSummaryResponse(val *GetWidgetSummaryResponse) *NullableGetWidgetSummaryResponse {
	return &NullableGetWidgetSummaryResponse{value: val, isSet: true}
}

func (v NullableGetWidgetSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWidgetSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


