/*
Linkbreakers API

This is a documentation of all the APIs of Linkbreakers

API version: 1.125.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkbreakers

import (
	"encoding/json"
)

// checks if the CreatePageThemeTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePageThemeTemplateRequest{}

// CreatePageThemeTemplateRequest CreatePageThemeTemplateRequest represents a request to create a new page theme template.  The template's styling is copied from an existing page theme, which is normally a link's theme the user wants to reuse. The copy is detached, so editing the link afterwards does not change the template.
type CreatePageThemeTemplateRequest struct {
	Description *string `json:"description,omitempty"`
	Faq *string `json:"faq,omitempty"`
	LearnMore *string `json:"learnMore,omitempty"`
	Name *string `json:"name,omitempty"`
	// Page theme to copy the styling from, usually a link's own theme. Omit to start from the default styling.
	SourcePageThemeId *string `json:"sourcePageThemeId,omitempty"`
	// Styling to capture, taking precedence over source_page_theme_id.  The editor sends what is on screen, so saving a theme as a template records the look the user is actually looking at rather than the last saved one.
	Styling *PageThemeStyling `json:"styling,omitempty"`
	Tags *string `json:"tags,omitempty"`
}

// NewCreatePageThemeTemplateRequest instantiates a new CreatePageThemeTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePageThemeTemplateRequest() *CreatePageThemeTemplateRequest {
	this := CreatePageThemeTemplateRequest{}
	return &this
}

// NewCreatePageThemeTemplateRequestWithDefaults instantiates a new CreatePageThemeTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePageThemeTemplateRequestWithDefaults() *CreatePageThemeTemplateRequest {
	this := CreatePageThemeTemplateRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreatePageThemeTemplateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetFaq returns the Faq field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetFaq() string {
	if o == nil || IsNil(o.Faq) {
		var ret string
		return ret
	}
	return *o.Faq
}

// GetFaqOk returns a tuple with the Faq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetFaqOk() (*string, bool) {
	if o == nil || IsNil(o.Faq) {
		return nil, false
	}
	return o.Faq, true
}

// HasFaq returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasFaq() bool {
	if o != nil && !IsNil(o.Faq) {
		return true
	}

	return false
}

// SetFaq gets a reference to the given string and assigns it to the Faq field.
func (o *CreatePageThemeTemplateRequest) SetFaq(v string) {
	o.Faq = &v
}

// GetLearnMore returns the LearnMore field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetLearnMore() string {
	if o == nil || IsNil(o.LearnMore) {
		var ret string
		return ret
	}
	return *o.LearnMore
}

// GetLearnMoreOk returns a tuple with the LearnMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetLearnMoreOk() (*string, bool) {
	if o == nil || IsNil(o.LearnMore) {
		return nil, false
	}
	return o.LearnMore, true
}

// HasLearnMore returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasLearnMore() bool {
	if o != nil && !IsNil(o.LearnMore) {
		return true
	}

	return false
}

// SetLearnMore gets a reference to the given string and assigns it to the LearnMore field.
func (o *CreatePageThemeTemplateRequest) SetLearnMore(v string) {
	o.LearnMore = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreatePageThemeTemplateRequest) SetName(v string) {
	o.Name = &v
}

// GetSourcePageThemeId returns the SourcePageThemeId field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetSourcePageThemeId() string {
	if o == nil || IsNil(o.SourcePageThemeId) {
		var ret string
		return ret
	}
	return *o.SourcePageThemeId
}

// GetSourcePageThemeIdOk returns a tuple with the SourcePageThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetSourcePageThemeIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourcePageThemeId) {
		return nil, false
	}
	return o.SourcePageThemeId, true
}

// HasSourcePageThemeId returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasSourcePageThemeId() bool {
	if o != nil && !IsNil(o.SourcePageThemeId) {
		return true
	}

	return false
}

// SetSourcePageThemeId gets a reference to the given string and assigns it to the SourcePageThemeId field.
func (o *CreatePageThemeTemplateRequest) SetSourcePageThemeId(v string) {
	o.SourcePageThemeId = &v
}

// GetStyling returns the Styling field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetStyling() PageThemeStyling {
	if o == nil || IsNil(o.Styling) {
		var ret PageThemeStyling
		return ret
	}
	return *o.Styling
}

// GetStylingOk returns a tuple with the Styling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetStylingOk() (*PageThemeStyling, bool) {
	if o == nil || IsNil(o.Styling) {
		return nil, false
	}
	return o.Styling, true
}

// HasStyling returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasStyling() bool {
	if o != nil && !IsNil(o.Styling) {
		return true
	}

	return false
}

// SetStyling gets a reference to the given PageThemeStyling and assigns it to the Styling field.
func (o *CreatePageThemeTemplateRequest) SetStyling(v PageThemeStyling) {
	o.Styling = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreatePageThemeTemplateRequest) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageThemeTemplateRequest) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreatePageThemeTemplateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *CreatePageThemeTemplateRequest) SetTags(v string) {
	o.Tags = &v
}

func (o CreatePageThemeTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePageThemeTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Faq) {
		toSerialize["faq"] = o.Faq
	}
	if !IsNil(o.LearnMore) {
		toSerialize["learnMore"] = o.LearnMore
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SourcePageThemeId) {
		toSerialize["sourcePageThemeId"] = o.SourcePageThemeId
	}
	if !IsNil(o.Styling) {
		toSerialize["styling"] = o.Styling
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableCreatePageThemeTemplateRequest struct {
	value *CreatePageThemeTemplateRequest
	isSet bool
}

func (v NullableCreatePageThemeTemplateRequest) Get() *CreatePageThemeTemplateRequest {
	return v.value
}

func (v *NullableCreatePageThemeTemplateRequest) Set(val *CreatePageThemeTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePageThemeTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePageThemeTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePageThemeTemplateRequest(val *CreatePageThemeTemplateRequest) *NullableCreatePageThemeTemplateRequest {
	return &NullableCreatePageThemeTemplateRequest{value: val, isSet: true}
}

func (v NullableCreatePageThemeTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePageThemeTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


